apiVersion: v1
kind: Service
metadata:
  name: postgres-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: postgres-gateway
    app.kubernetes.io/part-of: dsa
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgresql
      name: postgresql
  selector:
    app.kubernetes.io/name: postgres-gateway
