// Package compliance — pdf.go.
//
// Renders the compliance PDF using github.com/go-pdf/fpdf (maintained
// fork of the now-abandoned jung-kurt/gofpdf). The renderer is
// fail-closed at EVERY text emit: each render call funnels its string
// argument through compliance.AssertSection. On detection the function
// returns the error up the stack; the handler returns 500 + NO PDF
// bytes (Slice 6's reveal-raw fail-closed pattern carried into the
// PDF surface).
//
// Layout:
//
//	Page 1 (cover): customer name, date range, kit version,
//	                  dashboard version, image-digest manifest table,
//	                  caveat block.
//	Page 2+        : Category 1 (Art. 10 + 15 sanitizer) summary
//	                  with sanitizer-layer breakdown.
//	                Category 2 (Art. 12 + 14 evidence) summary with
//	                  cert verdict distribution.
//	                Category 3 (Art. 10 + 12 + 14 + 15 inventory)
//	                  summary with combined counts.
//	Footer (every page): "Generated by Lucairn Enterprise Dashboard
//	                  v<version> on <RFC3339>" + "Page N of M".
//
// The AI Act 3-category labels + their article pairings are LOCKED
// per CLAUDE.md § "Locked decisions" → "AI Act article pairings:
// three-category scheme". The PDF renders these strings VERBATIM; the
// regulator-validator agent on the reviewer chain will check this.
//
// Font choice: fpdf's default Helvetica is what we use. The kit's
// Lucairn brand fonts (Geist + Geist Mono + Bricolage) ship as woff2
// and would require ttf conversion + fpdf font setup at boot to be
// usable here — deferred. The visual treatment relies on Helvetica's
// weight + spacing for the same airy feel; the cover uses the Lucairn
// accent line at the top as the brand anchor.
//
// Deterministic output: fpdf's RNG is not used by the renderer; given
// the same input + the same generated_at timestamp, the bytes are
// byte-identical. CreationDate uses the supplied GeneratedAt so test
// builds are stable.

package compliance

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"

	"github.com/Declade/lucairn-enterprise-deployment-kit/apps/dashboard/internal/compliance/templates"
)

// PDFInput carries every input pdf.GeneratePDF reads. The aggregator
// produces ComplianceSummary; the handler composes PDFInput around it.
type PDFInput struct {
	CustomerName string
	KitVersion   string
	DashboardVer string
	GeneratedAt  time.Time
	ImageDigests map[string]string
	Summary      *ComplianceSummary
}

// MaxRenderedRowsPerSection bounds the per-section row count to keep
// the renderer's working set bounded against a 1M-row scan from a
// crafted query. ComplianceSummary's aggregator-side queries already
// project counts (not raw rows) so this is a defence-in-depth cap;
// hitting it surfaces as an "elided" caveat in the section body.
const MaxRenderedRowsPerSection = 10000

// GeneratePDF emits a complete compliance PDF as a byte slice. Returns
// the PDF bytes + page count, or an error.
//
// Fail-closed behaviour: ANY banned-literal detection during render
// returns the error immediately; partial bytes are NOT returned. The
// caller MUST 500 in this case.
func GeneratePDF(in PDFInput) ([]byte, int, error) {
	if in.Summary == nil {
		return nil, 0, fmt.Errorf("compliance: PDF requires a non-nil Summary")
	}

	// Pre-flight every operator-supplied string through the banned-
	// literal guard so a banned literal in the input fails-closed
	// BEFORE we open the fpdf document.
	for _, pair := range []struct {
		section string
		text    string
	}{
		{"input_customer_name", in.CustomerName},
		{"input_kit_version", in.KitVersion},
		{"input_dashboard_ver", in.DashboardVer},
	} {
		if err := AssertSection(pair.section, pair.text); err != nil {
			return nil, 0, err
		}
	}

	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetTitle("Lucairn Enterprise Dashboard - Compliance Export", false)
	pdf.SetSubject("AI Act Art. 10/12/14/15 evidence summary", false)
	pdf.SetAuthor("Lucairn Enterprise Dashboard", false)
	pdf.SetCreator(fmt.Sprintf("Lucairn Enterprise Dashboard %s", in.DashboardVer), false)
	pdf.SetCreationDate(in.GeneratedAt.UTC())
	pdf.SetMargins(20, 22, 20)
	pdf.SetAutoPageBreak(true, 22)

	// Footer carries page X of Y + generated timestamp. fpdf calls the
	// supplied SetFooterFunc on every AddPage before returning to the
	// caller's render flow.
	footerText := fmt.Sprintf("Generated by Lucairn Enterprise Dashboard v%s on %s", in.DashboardVer, in.GeneratedAt.UTC().Format(time.RFC3339))
	if err := AssertSection("footer", footerText); err != nil {
		return nil, 0, err
	}
	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(140, 140, 145)
		pdf.CellFormat(0, 5, footerText, "", 0, "L", false, 0, "")
		pageNo := fmt.Sprintf("Page %d of {nb}", pdf.PageNo())
		pdf.CellFormat(0, 5, pageNo, "", 1, "R", false, 0, "")
		pdf.SetTextColor(0, 0, 0)
	})
	pdf.AliasNbPages("")

	// Cover page.
	coverIn := templates.CoverInput{
		CustomerName:  in.CustomerName,
		DateRangeFrom: in.Summary.WindowFrom,
		DateRangeTo:   in.Summary.WindowTo,
		KitVersion:    in.KitVersion,
		DashboardVer:  in.DashboardVer,
		GeneratedAt:   in.GeneratedAt,
		ImageDigests:  in.ImageDigests,
	}
	if err := templates.Render(adaptFpdf(pdf), coverIn, AssertSection); err != nil {
		return nil, 0, err
	}

	// Body pages — one per AI Act category. Strict ordering: Cat 1 →
	// Cat 2 → Cat 3 per CLAUDE.md.
	if err := renderCategory1(pdf, in.Summary, in.CustomerName); err != nil {
		return nil, 0, err
	}
	if err := renderCategory2(pdf, in.Summary, in.CustomerName); err != nil {
		return nil, 0, err
	}
	if err := renderCategory3(pdf, in.Summary, in.CustomerName); err != nil {
		return nil, 0, err
	}

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, 0, fmt.Errorf("compliance: fpdf output: %w", err)
	}
	pageCount := pdf.PageNo()
	return buf.Bytes(), pageCount, nil
}

// renderCategory1 emits the Cat 1 page: Art. 10 + 15 sanitizer claims.
// The summary's sanitizer counts populate the layer table.
func renderCategory1(pdf *fpdf.Fpdf, s *ComplianceSummary, customerName string) error {
	const section = "Category 1 (Art. 10 + 15 sanitizer)"

	pdf.AddPage()
	if err := writeCategoryHeader(pdf, section, "Article 10 — data governance and training data quality. Article 15 — accuracy, robustness, and cybersecurity."); err != nil {
		return err
	}

	body := fmt.Sprintf("Sanitizer activity for %s during the window %s through %s (UTC). Each row counts emitted sanitizer events grouped by detection layer.",
		customerName,
		s.WindowFrom.Format("2006-01-02"),
		s.WindowTo.Add(-1*time.Nanosecond).Format("2006-01-02"),
	)
	if err := AssertSection(section, body); err != nil {
		return err
	}
	pdf.SetFont("Helvetica", "", 10)
	pdf.MultiCell(0, 5.5, body, "", "L", false)
	pdf.Ln(4)

	// Layer table.
	pdf.SetFont("Helvetica", "B", 10)
	if err := AssertSection(section+"/totals", fmt.Sprintf("Total sanitizer events: %d", s.Sanitizer.TotalRedactions)); err != nil {
		return err
	}
	pdf.CellFormat(0, 6, fmt.Sprintf("Total sanitizer events: %d", s.Sanitizer.TotalRedactions), "", 1, "L", false, 0, "")
	pdf.Ln(2)

	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(80, 6, "Detection layer", "B", 0, "L", false, 0, "")
	pdf.CellFormat(0, 6, "Events", "B", 1, "R", false, 0, "")

	pdf.SetFont("Helvetica", "", 10)
	keys := sortedMapKeys(s.Sanitizer.ByLayer)
	for i, k := range keys {
		if i >= MaxRenderedRowsPerSection {
			break
		}
		v := s.Sanitizer.ByLayer[k]
		label := k
		if label == "" {
			label = "(empty)"
		}
		line := fmt.Sprintf("%s -> %d", label, v)
		if err := AssertSection(section+"/row/"+label, line); err != nil {
			return err
		}
		pdf.CellFormat(80, 5.5, label, "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 5.5, fmt.Sprintf("%d", v), "", 1, "R", false, 0, "")
	}
	if len(keys) == 0 {
		pdf.CellFormat(0, 5.5, "(no sanitizer events recorded in this window)", "", 1, "L", false, 0, "")
	}
	if len(keys) > MaxRenderedRowsPerSection {
		pdf.SetFont("Helvetica", "I", 9)
		elided := fmt.Sprintf("(%d additional layer buckets elided to keep the section bounded)", len(keys)-MaxRenderedRowsPerSection)
		if err := AssertSection(section+"/elided", elided); err != nil {
			return err
		}
		pdf.CellFormat(0, 5.5, elided, "", 1, "L", false, 0, "")
	}

	return nil
}

// renderCategory2 emits the Cat 2 page: Art. 12 + 14 evidence claims.
// Populated by cert counts + verdict distribution.
func renderCategory2(pdf *fpdf.Fpdf, s *ComplianceSummary, customerName string) error {
	const section = "Category 2 (Art. 12 + 14 evidence)"

	pdf.AddPage()
	if err := writeCategoryHeader(pdf, section, "Article 12 — record-keeping and logging. Article 14 — human oversight."); err != nil {
		return err
	}

	body := fmt.Sprintf("Certificate evidence for %s during the window %s through %s (UTC). Each cert documents a pipeline run with bridge + sanitizer + sandbox-isolation claims signed by the Lucairn witness.",
		customerName,
		s.WindowFrom.Format("2006-01-02"),
		s.WindowTo.Add(-1*time.Nanosecond).Format("2006-01-02"),
	)
	if err := AssertSection(section, body); err != nil {
		return err
	}
	pdf.SetFont("Helvetica", "", 10)
	pdf.MultiCell(0, 5.5, body, "", "L", false)
	pdf.Ln(4)

	pdf.SetFont("Helvetica", "B", 10)
	totalsLine := fmt.Sprintf("Total certificates: %d", s.Certs.Total)
	if err := AssertSection(section+"/totals", totalsLine); err != nil {
		return err
	}
	pdf.CellFormat(0, 6, totalsLine, "", 1, "L", false, 0, "")
	pdf.Ln(2)

	// Verdict distribution table.
	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(80, 6, "Overall verdict", "B", 0, "L", false, 0, "")
	pdf.CellFormat(0, 6, "Certificates", "B", 1, "R", false, 0, "")

	pdf.SetFont("Helvetica", "", 10)
	keys := sortedMapKeys(s.Certs.ByVerdict)
	totalRows := 0
	for _, k := range keys {
		if totalRows >= MaxRenderedRowsPerSection {
			break
		}
		v := s.Certs.ByVerdict[k]
		line := fmt.Sprintf("%s -> %d", k, v)
		if err := AssertSection(section+"/row/"+k, line); err != nil {
			return err
		}
		pdf.CellFormat(80, 5.5, k, "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 5.5, fmt.Sprintf("%d", v), "", 1, "R", false, 0, "")
		totalRows++
	}
	if s.Certs.NoVerdict > 0 {
		line := fmt.Sprintf("(no verdict recorded) -> %d", s.Certs.NoVerdict)
		if err := AssertSection(section+"/noverdict", line); err != nil {
			return err
		}
		pdf.SetFont("Helvetica", "I", 10)
		pdf.CellFormat(80, 5.5, "(no verdict recorded)", "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 5.5, fmt.Sprintf("%d", s.Certs.NoVerdict), "", 1, "R", false, 0, "")
	}
	if len(keys) == 0 && s.Certs.NoVerdict == 0 {
		pdf.CellFormat(0, 5.5, "(no certificates recorded in this window)", "", 1, "L", false, 0, "")
	}

	return nil
}

// renderCategory3 emits the Cat 3 page: Art. 10 + 12 + 14 + 15
// inventory. This is the cross-cutting roll-up: audit-event volume by
// type.
func renderCategory3(pdf *fpdf.Fpdf, s *ComplianceSummary, customerName string) error {
	const section = "Category 3 (Art. 10 + 12 + 14 + 15 inventory)"

	pdf.AddPage()
	if err := writeCategoryHeader(pdf, section, "Cross-cutting inventory across Article 10 (data governance), 12 (logging), 14 (human oversight), 15 (robustness)."); err != nil {
		return err
	}

	body := fmt.Sprintf("Audit-event inventory for %s during the window %s through %s (UTC). Counts are derived from the audit_events stream.",
		customerName,
		s.WindowFrom.Format("2006-01-02"),
		s.WindowTo.Add(-1*time.Nanosecond).Format("2006-01-02"),
	)
	if err := AssertSection(section, body); err != nil {
		return err
	}
	pdf.SetFont("Helvetica", "", 10)
	pdf.MultiCell(0, 5.5, body, "", "L", false)
	pdf.Ln(4)

	pdf.SetFont("Helvetica", "B", 10)
	totalsLine := fmt.Sprintf("Total audit events: %d", s.Audit.Total)
	if err := AssertSection(section+"/totals", totalsLine); err != nil {
		return err
	}
	pdf.CellFormat(0, 6, totalsLine, "", 1, "L", false, 0, "")
	pdf.Ln(2)

	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(120, 6, "Event type", "B", 0, "L", false, 0, "")
	pdf.CellFormat(0, 6, "Count", "B", 1, "R", false, 0, "")

	pdf.SetFont("Helvetica", "", 10)
	keys := sortedMapKeys(s.Audit.ByType)
	for i, k := range keys {
		if i >= MaxRenderedRowsPerSection {
			break
		}
		v := s.Audit.ByType[k]
		line := fmt.Sprintf("%s -> %d", k, v)
		if err := AssertSection(section+"/row/"+k, line); err != nil {
			return err
		}
		pdf.CellFormat(120, 5.5, k, "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 5.5, fmt.Sprintf("%d", v), "", 1, "R", false, 0, "")
	}
	if len(keys) == 0 {
		pdf.CellFormat(0, 5.5, "(no audit events recorded in this window)", "", 1, "L", false, 0, "")
	}
	if len(keys) > MaxRenderedRowsPerSection {
		pdf.SetFont("Helvetica", "I", 9)
		elided := fmt.Sprintf("(%d additional event-type rows elided to keep the section bounded)", len(keys)-MaxRenderedRowsPerSection)
		if err := AssertSection(section+"/elided", elided); err != nil {
			return err
		}
		pdf.CellFormat(0, 5.5, elided, "", 1, "L", false, 0, "")
	}

	return nil
}

// writeCategoryHeader emits the section title bar + subtitle. Both
// run through the banned-literal guard.
func writeCategoryHeader(pdf *fpdf.Fpdf, title, subtitle string) error {
	if err := AssertSection(title+"/title", title); err != nil {
		return err
	}
	if err := AssertSection(title+"/subtitle", subtitle); err != nil {
		return err
	}
	pdf.SetTextColor(20, 20, 22)
	pdf.SetFont("Helvetica", "B", 16)
	pdf.CellFormat(0, 9, title, "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 115)
	pdf.MultiCell(0, 5, subtitle, "", "L", false)
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(2)
	// Accent underline.
	pdf.SetDrawColor(142, 192, 240)
	pdf.SetLineWidth(0.3)
	y := pdf.GetY()
	pageW, _ := pdf.GetPageSize()
	pdf.Line(20, y, pageW-20, y)
	pdf.SetDrawColor(0, 0, 0)
	pdf.Ln(4)
	return nil
}

// sortedMapKeys is a small helper so the cert/sanitizer/audit tables
// have a stable row ordering across builds (Go map iteration is
// non-deterministic; the PDF should be byte-identical given identical
// inputs).
func sortedMapKeys(m map[string]int) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// adaptFpdf wraps a *fpdf.Fpdf into the templates.CoverRenderer
// interface. The two adapter methods (Ln, PageWidth) compensate for
// fpdf's slightly different shape — Ln takes a float64 but its
// behaviour is identical, and PageWidth() returns the A4 width
// dynamically.
func adaptFpdf(p *fpdf.Fpdf) templates.CoverRenderer {
	return &fpdfAdapter{p: p}
}

type fpdfAdapter struct {
	p *fpdf.Fpdf
}

func (a *fpdfAdapter) AddPage()                                     { a.p.AddPage() }
func (a *fpdfAdapter) SetFont(family, style string, sizePt float64) { a.p.SetFont(family, style, sizePt) }
func (a *fpdfAdapter) SetTextColor(r, g, b int)                     { a.p.SetTextColor(r, g, b) }
func (a *fpdfAdapter) SetDrawColor(r, g, b int)                     { a.p.SetDrawColor(r, g, b) }
func (a *fpdfAdapter) SetLineWidth(w float64)                       { a.p.SetLineWidth(w) }
func (a *fpdfAdapter) SetY(y float64)                               { a.p.SetY(y) }
func (a *fpdfAdapter) SetX(x float64)                               { a.p.SetX(x) }
func (a *fpdfAdapter) GetX() float64                                { return a.p.GetX() }
func (a *fpdfAdapter) GetY() float64                                { return a.p.GetY() }
func (a *fpdfAdapter) Line(x1, y1, x2, y2 float64)                  { a.p.Line(x1, y1, x2, y2) }
func (a *fpdfAdapter) Ln(h float64)                                 { a.p.Ln(h) }
func (a *fpdfAdapter) PageWidth() float64 {
	w, _ := a.p.GetPageSize()
	return w
}
func (a *fpdfAdapter) CellFormat(w, h float64, text, border string, ln int, align string, fill bool, link int, linkStr string) {
	a.p.CellFormat(w, h, text, border, ln, align, fill, link, linkStr)
}
func (a *fpdfAdapter) MultiCell(w, h float64, text, border, align string, fill bool) {
	a.p.MultiCell(w, h, text, border, align, fill)
}

// SanitizeFilename returns a safe Content-Disposition filename for the
// PDF download. Replaces spaces with dashes, strips path separators +
// other suspect characters, lower-cases the customer slug.
func SanitizeFilename(customerName string, from, to time.Time) string {
	slug := strings.ToLower(strings.TrimSpace(customerName))
	var b strings.Builder
	b.Grow(len(slug))
	for _, r := range slug {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == ' ' || r == '-' || r == '_':
			b.WriteRune('-')
		default:
			// Drop everything else.
		}
	}
	customerPart := b.String()
	if customerPart == "" {
		customerPart = "customer"
	}
	return fmt.Sprintf("lucairn-compliance-%s-%s-%s.pdf",
		customerPart,
		from.UTC().Format("20060102"),
		to.UTC().Format("20060102"),
	)
}
