package testutil

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"

	witnesspb "github.com/Declade/lucairn-enterprise-deployment-kit/apps/dashboard/internal/witness/pb"
)

// ---------------------------------------------------------------------------
// Fixtures for the T-600 / T-617 coverage records.
// ---------------------------------------------------------------------------
//
// testdata/l3_evidence_producer_payloads.json is a VERBATIM copy of the
// upstream producer-shape corpus:
//
//	Declade/dual-sandbox-architecture @ 91941304fd3ba30779d81121c37c436a631f4089
//	services/veil-witness/internal/verifier/testdata/l3_evidence_producer_payloads.json
//	(generated by that repo's testdata/gen_l3_evidence_fixtures.py from
//	 services/sanitizer/l3_evidence_probe.py — the real producer)
//
// ⚑ WHY COPY THE PRODUCER CORPUS INTO A CONSUMER'S TESTS. The dashboard never
// sees a producer payload: it sees the WITNESS's typed VerificationResult. But
// the per-field numbers in that typed message are reproduced verbatim from the
// producer record, so a fixture invented here could drift into shapes the
// producer cannot emit — and a render test over an impossible record proves
// nothing about the page an operator will actually read. The per-field rows
// below come from the producer corpus; only the witness-computed rollups are
// derived here, from the rule documented on the proto.
//
// ⛔ THIS IS NOT A REIMPLEMENTATION OF THE WITNESS. l3EvidenceRollup folds the
// per-field verdicts with the lattice the proto documents
// (L3CoverageEvidence.rollup, upstream verifier l3EvidenceRollup) purely to
// BUILD a realistic input. The dashboard derives nothing at runtime; it renders
// what the witness sends. If upstream ever changes the fold these fixtures
// become wrong in a way the contract-drift-detector is expected to catch — they
// are fixtures, not a second source of truth.

// ProducerFieldEvidence is one field's entry in the producer corpus.
type ProducerFieldEvidence struct {
	CanariesPlanted   uint32 `json:"canaries_planted"`
	CanariesRecovered uint32 `json:"canaries_recovered"`
	DerivationVersion string `json:"derivation_version"`
	DrivesClaim       bool   `json:"drives_claim"`
	ProbedWindows     uint32 `json:"probed_windows"`
	Reason            string `json:"reason"`
	Verdict           string `json:"verdict"`
	Windows           uint32 `json:"windows"`
}

type producerCorpus struct {
	DerivationVersion string                                      `json:"_derivation_version"`
	Scenarios         map[string]map[string]ProducerFieldEvidence `json:"scenarios"`
}

// producerCorpusPath resolves testdata relative to THIS source file, so
// callers in other packages (handlers, witness) get the same corpus without
// each one carrying a ../.. path that breaks when a test file moves.
func producerCorpusPath() (string, error) {
	_, self, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("testutil: cannot resolve own source path")
	}
	return filepath.Join(filepath.Dir(self), "testdata", "l3_evidence_producer_payloads.json"), nil
}

func loadProducerCorpus() (producerCorpus, error) {
	var c producerCorpus
	path, err := producerCorpusPath()
	if err != nil {
		return c, err
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return c, fmt.Errorf("testutil: read producer corpus: %w", err)
	}
	if err := json.Unmarshal(raw, &c); err != nil {
		return c, fmt.Errorf("testutil: parse producer corpus: %w", err)
	}
	if c.DerivationVersion == "" {
		return c, fmt.Errorf("testutil: producer corpus carries no _derivation_version")
	}
	return c, nil
}

// L3EvidenceFromProducer builds the witness-shaped L3CoverageEvidence a real
// witness would emit for one scenario of the producer corpus. Scenario names
// are the upstream ones: passed, failed, mixed, partial, empty, probe_off,
// absent_cached, absent_below_floor, absent_no_window,
// absent_headroom_clipped, absent_no_prompt_seam.
func L3EvidenceFromProducer(scenario string) (*witnesspb.L3CoverageEvidence, error) {
	c, err := loadProducerCorpus()
	if err != nil {
		return nil, err
	}
	entries, ok := c.Scenarios[scenario]
	if !ok {
		return nil, fmt.Errorf("testutil: producer corpus has no scenario %q", scenario)
	}

	keys := make([]string, 0, len(entries))
	for k := range entries {
		keys = append(keys, k)
	}
	sort.Strings(keys) // the witness emits `fields` sorted by field_key.

	ev := &witnesspb.L3CoverageEvidence{
		RecordStatus:      "present",
		DerivationVersion: c.DerivationVersion,
		// ⛔ Hard-staged false upstream (TestL3Evidence_DrivesVerdictStaysFalse).
		DrivesVerdict: false,
	}
	for _, k := range keys {
		e := entries[k]
		ev.Fields = append(ev.Fields, &witnesspb.L3FieldEvidence{
			FieldKey:          k,
			Verdict:           e.Verdict,
			Reason:            e.Reason,
			CanariesPlanted:   e.CanariesPlanted,
			CanariesRecovered: e.CanariesRecovered,
			Windows:           e.Windows,
			ProbedWindows:     e.ProbedWindows,
		})
		ev.CanariesPlanted += e.CanariesPlanted
		ev.CanariesRecovered += e.CanariesRecovered
		switch e.Verdict {
		case "passed":
			ev.FieldsPassed++
		case "failed":
			ev.FieldsFailed++
		case "absent":
			ev.FieldsAbsent++
		default:
			return nil, fmt.Errorf("testutil: scenario %q field %q: out-of-vocabulary verdict %q", scenario, k, e.Verdict)
		}
	}
	ev.Rollup = l3EvidenceRollup(ev.FieldsPassed, ev.FieldsFailed, ev.FieldsAbsent)
	return ev, nil
}

// l3EvidenceRollup mirrors the documented fold (proto L3CoverageEvidence.rollup).
func l3EvidenceRollup(passed, failed, absent uint32) string {
	switch {
	case failed > 0:
		return "failed"
	case passed == 0:
		return "absent"
	case absent > 0:
		return "unverified"
	default:
		return "verified"
	}
}

// L3ScopeGranted is a present, granting scope record over the given
// freshly-scanned field keys plus the given policy exclusions.
func L3ScopeGranted(fieldKeys []string, excluded []*witnesspb.L3ExcludedField) *witnesspb.L3CoverageScope {
	sc := &witnesspb.L3CoverageScope{
		RecordStatus:      "present",
		DerivationVersion: "t617-scope-v1",
		DrivesClaim:       false,
		Granted:           true,
		Reason:            "all_eligible_fields_covered",
		EligibleCount:     uint32(len(fieldKeys)),
		Excluded:          excluded,
	}
	for _, k := range fieldKeys {
		sc.Covered = append(sc.Covered, &witnesspb.L3CoveredField{FieldKey: k, Via: "scan"})
	}
	return sc
}
