{{- if ne .Values.secrets.backend "k8s-native" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: dsa
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: dsa-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Chart.Name }}-credentials
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        {{- if eq .Values.secrets.backend "vault" }}
        key: {{ .Values.secrets.vault.path }}
        property: url
        {{- else if eq .Values.secrets.backend "aws" }}
        key: {{ .Values.secrets.aws.name }}
        property: url
        {{- else if eq .Values.secrets.backend "azure" }}
        key: {{ .Values.secrets.azure.name }}
        property: url
        {{- end }}
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        {{- if eq .Values.secrets.backend "vault" }}
        key: {{ .Values.secrets.vault.path }}
        property: password
        {{- else if eq .Values.secrets.backend "aws" }}
        key: {{ .Values.secrets.aws.name }}
        property: password
        {{- else if eq .Values.secrets.backend "azure" }}
        key: {{ .Values.secrets.azure.name }}
        property: password
        {{- end }}
    - secretKey: VEIL_SIGNING_KEY
      remoteRef:
        {{- if eq .Values.secrets.backend "vault" }}
        key: {{ .Values.secrets.vault.path }}
        property: veilSigningKey
        {{- else if eq .Values.secrets.backend "aws" }}
        key: {{ .Values.secrets.aws.name }}
        property: veilSigningKey
        {{- else if eq .Values.secrets.backend "azure" }}
        key: {{ .Values.secrets.azure.name }}
        property: veilSigningKey
        {{- end }}
    - secretKey: DSA_SERVICE_TOKEN
      remoteRef:
        {{- if eq .Values.secrets.backend "vault" }}
        key: {{ .Values.secrets.vault.path }}
        property: dsaServiceToken
        {{- else if eq .Values.secrets.backend "aws" }}
        key: {{ .Values.secrets.aws.name }}
        property: dsaServiceToken
        {{- else if eq .Values.secrets.backend "azure" }}
        key: {{ .Values.secrets.azure.name }}
        property: dsaServiceToken
        {{- end }}
{{- end }}
