{{- if .Values.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-redis-data
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-redis
    app.kubernetes.io/part-of: dsa
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.redis.storageClass }}
  storageClassName: {{ .Values.redis.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.storageSize }}
{{- end }}
