// Minimal Lucairn Witness gRPC contract used by the dashboard's cert
// inspector + validator. Vendored intentionally as a SUBSET of the
// upstream `services/veil-witness/api/witness.proto` schema; only the
// fields the dashboard's cert browser + inspector + audit-grade validator
// surfaces are kept here.
//
// Upstream source the wire format MUST stay byte-compatible with:
//   Declade/dual-sandbox-architecture/services/veil-witness/api/witness.proto
//   (CertServer.VerifyCertificate at internal/server/cert_server.go:201 ―
//   per PRD prd-2026-05-17-enterprise-dashboard.md § D7).
//
// Cross-language byte equality with the witness service is REQUIRED — the
// dashboard reconstructs the cert envelope from the same per-claim signed
// canonical bytes. Field numbers, enum values, and oneof tags must remain
// IDENTICAL to upstream. If a field is unknown to this proto, the gRPC
// payload still decodes (unknown fields are preserved by protobuf
// semantics) — but expanding our view of any new field MUST be a
// coordinated edit on both repos.
//
// Out of scope here: AssembleCertificate, ListCertificates, mintEvidence
// — those RPCs run server-side only. The dashboard never calls them.
//
// Update protocol: bump major + regenerate pb stubs via
//   cd apps/dashboard
//   protoc --go_out=. --go_opt=paths=source_relative \
//          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//          internal/witness/witness.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: witness.proto

package witnesspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cert_id is the UUID under which the cert was stored in the audit /
	// bridge Postgres. Required.
	CertId        string `protobuf:"bytes,1,opt,name=cert_id,json=certId,proto3" json:"cert_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCertificateRequest) Reset() {
	*x = VerifyCertificateRequest{}
	mi := &file_witness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCertificateRequest) ProtoMessage() {}

func (x *VerifyCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCertificateRequest.ProtoReflect.Descriptor instead.
func (*VerifyCertificateRequest) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyCertificateRequest) GetCertId() string {
	if x != nil {
		return x.CertId
	}
	return ""
}

// VerifyCertificateResponse is the dashboard-facing subset of the witness
// proto. Unknown fields beyond these are preserved on the wire but not
// surfaced in the UI until a coordinated proto bump lands.
type VerifyCertificateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// overall_verdict is the verifier's headline conclusion. Values:
	//
	//	"verified" / "partial" / "failed" / "byok_exempt"
	//
	// BYOK_EXEMPT runs (per dual-sandbox-architecture PR #152) MUST be
	// surfaced as "verified" with byok_exempt = true so the audit reader
	// sees the right semantic verdict.
	OverallVerdict string `protobuf:"bytes,1,opt,name=overall_verdict,json=overallVerdict,proto3" json:"overall_verdict,omitempty"`
	// completeness reports which claims are present. "full" = all 6 claim
	// types present; "partial" = bridge + sanitizer present, sandbox-* may
	// be absent on BYOK_EXEMPT runs.
	Completeness string `protobuf:"bytes,2,opt,name=completeness,proto3" json:"completeness,omitempty"`
	// signatures_valid is true iff every per-claim Ed25519 signature
	// verified against the witness-anchored public key set.
	SignaturesValid bool `protobuf:"varint,3,opt,name=signatures_valid,json=signaturesValid,proto3" json:"signatures_valid,omitempty"`
	// byok_exempt is set when this cert was produced by a BYOK run (the
	// customer's own upstream LLM key was forwarded by the gateway; the
	// managed sandbox-b never ran for the inference claim). isolation_verified
	// remains true in this case — see CLAUDE.md § BYOK_EXEMPT.
	ByokExempt bool `protobuf:"varint,4,opt,name=byok_exempt,json=byokExempt,proto3" json:"byok_exempt,omitempty"`
	// isolation_verified mirrors the dual-sandbox-architecture invariant:
	// raw identity data was never exposed to the AI service on this run.
	IsolationVerified bool `protobuf:"varint,5,opt,name=isolation_verified,json=isolationVerified,proto3" json:"isolation_verified,omitempty"`
	// tsa_timestamp is the RFC 3161 timestamp envelope URL or value the
	// dashboard deep-links to (FreeTSA per CLAUDE.md sub-processors).
	TsaTimestamp string `protobuf:"bytes,6,opt,name=tsa_timestamp,json=tsaTimestamp,proto3" json:"tsa_timestamp,omitempty"`
	// rekor_uuid is the Sigstore Rekor entry UUID the dashboard deep-links
	// to. May be empty during the transition window after audit-trail wave.
	RekorUuid string `protobuf:"bytes,7,opt,name=rekor_uuid,json=rekorUuid,proto3" json:"rekor_uuid,omitempty"`
	// per_claim is one entry per claim type. UI renders these in the locked
	// order: gateway, bridge, sanitizer, sandbox-a, sandbox-b, witness.
	PerClaim []*PerClaimVerdict `protobuf:"bytes,8,rep,name=per_claim,json=perClaim,proto3" json:"per_claim,omitempty"`
	// cert_url is the canonical browser-visible URL for this cert (used by
	// the UI as a copy-and-share anchor). Optional; the UI synthesizes one
	// from the cert id when this is empty.
	CertUrl string `protobuf:"bytes,9,opt,name=cert_url,json=certUrl,proto3" json:"cert_url,omitempty"`
	// error is set when the witness can answer the verify request but
	// recovered a fail-to-verify path (e.g. signature mismatch on a claim).
	// The dashboard renders this verbatim in the inspector's failure panel.
	Error         string `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCertificateResponse) Reset() {
	*x = VerifyCertificateResponse{}
	mi := &file_witness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCertificateResponse) ProtoMessage() {}

func (x *VerifyCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCertificateResponse.ProtoReflect.Descriptor instead.
func (*VerifyCertificateResponse) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyCertificateResponse) GetOverallVerdict() string {
	if x != nil {
		return x.OverallVerdict
	}
	return ""
}

func (x *VerifyCertificateResponse) GetCompleteness() string {
	if x != nil {
		return x.Completeness
	}
	return ""
}

func (x *VerifyCertificateResponse) GetSignaturesValid() bool {
	if x != nil {
		return x.SignaturesValid
	}
	return false
}

func (x *VerifyCertificateResponse) GetByokExempt() bool {
	if x != nil {
		return x.ByokExempt
	}
	return false
}

func (x *VerifyCertificateResponse) GetIsolationVerified() bool {
	if x != nil {
		return x.IsolationVerified
	}
	return false
}

func (x *VerifyCertificateResponse) GetTsaTimestamp() string {
	if x != nil {
		return x.TsaTimestamp
	}
	return ""
}

func (x *VerifyCertificateResponse) GetRekorUuid() string {
	if x != nil {
		return x.RekorUuid
	}
	return ""
}

func (x *VerifyCertificateResponse) GetPerClaim() []*PerClaimVerdict {
	if x != nil {
		return x.PerClaim
	}
	return nil
}

func (x *VerifyCertificateResponse) GetCertUrl() string {
	if x != nil {
		return x.CertUrl
	}
	return ""
}

func (x *VerifyCertificateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PerClaimVerdict captures one slot in the 6-row claim chain.
type PerClaimVerdict struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// claim_type is one of: "gateway", "bridge", "sanitizer",
	// "sandbox_a", "sandbox_b", "witness".
	ClaimType string `protobuf:"bytes,1,opt,name=claim_type,json=claimType,proto3" json:"claim_type,omitempty"`
	// verdict is "ok" or "fail". The UI renders an "ok"-pill or "fail"-pill
	// accordingly; semantic-status colors only.
	Verdict string `protobuf:"bytes,2,opt,name=verdict,proto3" json:"verdict,omitempty"`
	// pub_key_fingerprint is the SHA-256 of the claim's Ed25519 public
	// key, hex-encoded. The UI surfaces the first 16 hex chars in the pill;
	// the click-to-reveal flow shows the full fingerprint.
	PubKeyFingerprint string `protobuf:"bytes,3,opt,name=pub_key_fingerprint,json=pubKeyFingerprint,proto3" json:"pub_key_fingerprint,omitempty"`
	// signature_hex is the full per-claim signature, hex-encoded. UI
	// surfaces the first 16 hex chars in the pill + ellipsis; click-to-reveal
	// shows the full bytes. NEVER store / log this string outside of the
	// verify-response cache.
	SignatureHex string `protobuf:"bytes,4,opt,name=signature_hex,json=signatureHex,proto3" json:"signature_hex,omitempty"`
	// canonical_payload_hash is the SHA-256 of the canonical signed bytes
	// for this claim, hex-encoded. Used by audit-grade investigators who
	// want to reconstruct the canonical bytes offline.
	CanonicalPayloadHash string `protobuf:"bytes,5,opt,name=canonical_payload_hash,json=canonicalPayloadHash,proto3" json:"canonical_payload_hash,omitempty"`
	// error is set when this claim failed verification. The UI renders this
	// verbatim under the pill so the operator can immediately see why a
	// single claim flipped to red.
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerClaimVerdict) Reset() {
	*x = PerClaimVerdict{}
	mi := &file_witness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerClaimVerdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerClaimVerdict) ProtoMessage() {}

func (x *PerClaimVerdict) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerClaimVerdict.ProtoReflect.Descriptor instead.
func (*PerClaimVerdict) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{2}
}

func (x *PerClaimVerdict) GetClaimType() string {
	if x != nil {
		return x.ClaimType
	}
	return ""
}

func (x *PerClaimVerdict) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *PerClaimVerdict) GetPubKeyFingerprint() string {
	if x != nil {
		return x.PubKeyFingerprint
	}
	return ""
}

func (x *PerClaimVerdict) GetSignatureHex() string {
	if x != nil {
		return x.SignatureHex
	}
	return ""
}

func (x *PerClaimVerdict) GetCanonicalPayloadHash() string {
	if x != nil {
		return x.CanonicalPayloadHash
	}
	return ""
}

func (x *PerClaimVerdict) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_witness_proto protoreflect.FileDescriptor

const file_witness_proto_rawDesc = "" +
	"\n" +
	"\rwitness.proto\x12\x12lucairn.witness.v1\"3\n" +
	"\x18VerifyCertificateRequest\x12\x17\n" +
	"\acert_id\x18\x01 \x01(\tR\x06certId\"\x9a\x03\n" +
	"\x19VerifyCertificateResponse\x12'\n" +
	"\x0foverall_verdict\x18\x01 \x01(\tR\x0eoverallVerdict\x12\"\n" +
	"\fcompleteness\x18\x02 \x01(\tR\fcompleteness\x12)\n" +
	"\x10signatures_valid\x18\x03 \x01(\bR\x0fsignaturesValid\x12\x1f\n" +
	"\vbyok_exempt\x18\x04 \x01(\bR\n" +
	"byokExempt\x12-\n" +
	"\x12isolation_verified\x18\x05 \x01(\bR\x11isolationVerified\x12#\n" +
	"\rtsa_timestamp\x18\x06 \x01(\tR\ftsaTimestamp\x12\x1d\n" +
	"\n" +
	"rekor_uuid\x18\a \x01(\tR\trekorUuid\x12@\n" +
	"\tper_claim\x18\b \x03(\v2#.lucairn.witness.v1.PerClaimVerdictR\bperClaim\x12\x19\n" +
	"\bcert_url\x18\t \x01(\tR\acertUrl\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"\xeb\x01\n" +
	"\x0fPerClaimVerdict\x12\x1d\n" +
	"\n" +
	"claim_type\x18\x01 \x01(\tR\tclaimType\x12\x18\n" +
	"\averdict\x18\x02 \x01(\tR\averdict\x12.\n" +
	"\x13pub_key_fingerprint\x18\x03 \x01(\tR\x11pubKeyFingerprint\x12#\n" +
	"\rsignature_hex\x18\x04 \x01(\tR\fsignatureHex\x124\n" +
	"\x16canonical_payload_hash\x18\x05 \x01(\tR\x14canonicalPayloadHash\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error2\x80\x01\n" +
	"\fCertVerifier\x12p\n" +
	"\x11VerifyCertificate\x12,.lucairn.witness.v1.VerifyCertificateRequest\x1a-.lucairn.witness.v1.VerifyCertificateResponseBcZagithub.com/Declade/lucairn-enterprise-deployment-kit/apps/dashboard/internal/witness/pb;witnesspbb\x06proto3"

var (
	file_witness_proto_rawDescOnce sync.Once
	file_witness_proto_rawDescData []byte
)

func file_witness_proto_rawDescGZIP() []byte {
	file_witness_proto_rawDescOnce.Do(func() {
		file_witness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_witness_proto_rawDesc), len(file_witness_proto_rawDesc)))
	})
	return file_witness_proto_rawDescData
}

var file_witness_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_witness_proto_goTypes = []any{
	(*VerifyCertificateRequest)(nil),  // 0: lucairn.witness.v1.VerifyCertificateRequest
	(*VerifyCertificateResponse)(nil), // 1: lucairn.witness.v1.VerifyCertificateResponse
	(*PerClaimVerdict)(nil),           // 2: lucairn.witness.v1.PerClaimVerdict
}
var file_witness_proto_depIdxs = []int32{
	2, // 0: lucairn.witness.v1.VerifyCertificateResponse.per_claim:type_name -> lucairn.witness.v1.PerClaimVerdict
	0, // 1: lucairn.witness.v1.CertVerifier.VerifyCertificate:input_type -> lucairn.witness.v1.VerifyCertificateRequest
	1, // 2: lucairn.witness.v1.CertVerifier.VerifyCertificate:output_type -> lucairn.witness.v1.VerifyCertificateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_witness_proto_init() }
func file_witness_proto_init() {
	if File_witness_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_witness_proto_rawDesc), len(file_witness_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_witness_proto_goTypes,
		DependencyIndexes: file_witness_proto_depIdxs,
		MessageInfos:      file_witness_proto_msgTypes,
	}.Build()
	File_witness_proto = out.File
	file_witness_proto_goTypes = nil
	file_witness_proto_depIdxs = nil
}
