// Minimal Lucairn Witness gRPC contract used by the dashboard's cert
// inspector + validator. Vendored intentionally as a SUBSET of the
// upstream `services/veil-witness/api/witness.proto` schema; only the
// fields the dashboard's cert browser + inspector + audit-grade validator
// surfaces are kept here.
//
// Upstream source the wire format MUST stay byte-compatible with:
//   Declade/dual-sandbox-architecture/services/veil-witness/api/witness.proto
//   (CertServer.VerifyCertificate at internal/server/cert_server.go:201 ―
//   per PRD prd-2026-05-17-enterprise-dashboard.md § D7).
//
// Cross-language byte equality with the witness service is REQUIRED — the
// dashboard reconstructs the cert envelope from the same per-claim signed
// canonical bytes. Field numbers, enum values, and oneof tags must remain
// IDENTICAL to upstream. If a field is unknown to this proto, the gRPC
// payload still decodes (unknown fields are preserved by protobuf
// semantics) — but expanding our view of any new field MUST be a
// coordinated edit on both repos.
//
// Out of scope here: AssembleCertificate, ListCertificates, mintEvidence
// — those RPCs run server-side only. The dashboard never calls them.
//
// Update protocol: bump major + regenerate pb stubs via
//   cd apps/dashboard
//   protoc --go_out=. --go_opt=paths=source_relative \
//          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//          internal/witness/witness.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: witness.proto

package witnesspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CertVerifier_VerifyCertificate_FullMethodName = "/lucairn.witness.v1.CertVerifier/VerifyCertificate"
)

// CertVerifierClient is the client API for CertVerifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CertVerifier is the SUBSET of the upstream witness gRPC surface the
// dashboard consumes. Backend service exposed on tcp/50051 by default.
type CertVerifierClient interface {
	// VerifyCertificate validates a single cert by its UUID. The witness
	// performs:
	//   - reconstruction of the canonical bytes per claim
	//   - Ed25519 signature verification per claim
	//   - chain integrity check (claim hashes link)
	//   - TSA timestamp envelope check (RFC 3161)
	//   - Sigstore Rekor inclusion-proof check
	//
	// Returns a structured per-claim verdict. Network / DB / decode errors
	// come back as gRPC status; the dashboard surfaces those as a
	// degraded-state badge ("Witness unreachable") rather than crashing.
	VerifyCertificate(ctx context.Context, in *VerifyCertificateRequest, opts ...grpc.CallOption) (*VerifyCertificateResponse, error)
}

type certVerifierClient struct {
	cc grpc.ClientConnInterface
}

func NewCertVerifierClient(cc grpc.ClientConnInterface) CertVerifierClient {
	return &certVerifierClient{cc}
}

func (c *certVerifierClient) VerifyCertificate(ctx context.Context, in *VerifyCertificateRequest, opts ...grpc.CallOption) (*VerifyCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyCertificateResponse)
	err := c.cc.Invoke(ctx, CertVerifier_VerifyCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertVerifierServer is the server API for CertVerifier service.
// All implementations must embed UnimplementedCertVerifierServer
// for forward compatibility.
//
// CertVerifier is the SUBSET of the upstream witness gRPC surface the
// dashboard consumes. Backend service exposed on tcp/50051 by default.
type CertVerifierServer interface {
	// VerifyCertificate validates a single cert by its UUID. The witness
	// performs:
	//   - reconstruction of the canonical bytes per claim
	//   - Ed25519 signature verification per claim
	//   - chain integrity check (claim hashes link)
	//   - TSA timestamp envelope check (RFC 3161)
	//   - Sigstore Rekor inclusion-proof check
	//
	// Returns a structured per-claim verdict. Network / DB / decode errors
	// come back as gRPC status; the dashboard surfaces those as a
	// degraded-state badge ("Witness unreachable") rather than crashing.
	VerifyCertificate(context.Context, *VerifyCertificateRequest) (*VerifyCertificateResponse, error)
	mustEmbedUnimplementedCertVerifierServer()
}

// UnimplementedCertVerifierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCertVerifierServer struct{}

func (UnimplementedCertVerifierServer) VerifyCertificate(context.Context, *VerifyCertificateRequest) (*VerifyCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyCertificate not implemented")
}
func (UnimplementedCertVerifierServer) mustEmbedUnimplementedCertVerifierServer() {}
func (UnimplementedCertVerifierServer) testEmbeddedByValue()                      {}

// UnsafeCertVerifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertVerifierServer will
// result in compilation errors.
type UnsafeCertVerifierServer interface {
	mustEmbedUnimplementedCertVerifierServer()
}

func RegisterCertVerifierServer(s grpc.ServiceRegistrar, srv CertVerifierServer) {
	// If the following call panics, it indicates UnimplementedCertVerifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CertVerifier_ServiceDesc, srv)
}

func _CertVerifier_VerifyCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertVerifierServer).VerifyCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertVerifier_VerifyCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertVerifierServer).VerifyCertificate(ctx, req.(*VerifyCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CertVerifier_ServiceDesc is the grpc.ServiceDesc for CertVerifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CertVerifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lucairn.witness.v1.CertVerifier",
	HandlerType: (*CertVerifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyCertificate",
			Handler:    _CertVerifier_VerifyCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "witness.proto",
}
