// Vendored from Declade/dual-sandbox-architecture:
//   proto/veil/v1/veil.proto @ commit f24bf0d2565ff5d414c0ee13c3188675d8f67d3c
// + proto/common/v1/types.proto (only EntityCount inlined, for SanitizerClaim).
//
// This file is the CANONICAL upstream `dsa.veil.v1` schema, vendored
// verbatim so the dashboard speaks the real witness gRPC contract:
//   service VeilCertificateService { GetCertificate, VerifyCertificate, ... }
// NOT the previous (invented) `lucairn.witness.v1.CertVerifier` shape,
// which empirically returned codes.Unimplemented against a real witness.
//
// KEEP IN SYNC: when the upstream proto field numbers or message names
// change, regenerate via:
//   make -C apps/dashboard proto-sync
// (or directly:)
//   protoc --proto_path=internal/witness \
//     --go_out=internal/witness/pb --go_opt=paths=source_relative \
//     --go-grpc_out=internal/witness/pb --go-grpc_opt=paths=source_relative \
//     internal/witness/witness.proto
//
// The contract-drift-detector subagent runs against every Slice-touching
// PR; expect it to flag any drift between this vendored copy and upstream.
// The Go-level regression test TestVerify_RealUpstreamServiceShape
// (verify_client_test.go) locks the fully-qualified method names dialed
// so a future copy-paste typo in this file is caught at unit-test time.
//
// Cross-language byte equality with the witness service is REQUIRED —
// the witness reconstructs the per-claim canonical bytes from THIS schema
// when it Verifies; we don't canonicalize anything on the dashboard side
// (we just round-trip the envelope). Field numbers, enum values, oneof
// tags MUST remain IDENTICAL to upstream.
//
// Out of scope here: VeilWitnessService.SubmitClaim — that RPC is the
// per-service emit path; the dashboard never calls it. It is intentionally
// omitted from this vendored copy. If the upstream witness ever adds a
// dashboard-facing RPC under VeilWitnessService, regenerate this file.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: witness.proto

package witnesspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VeilCertificateService_GetCertificate_FullMethodName     = "/dsa.veil.v1.VeilCertificateService/GetCertificate"
	VeilCertificateService_ExportCertificates_FullMethodName = "/dsa.veil.v1.VeilCertificateService/ExportCertificates"
	VeilCertificateService_VerifyCertificate_FullMethodName  = "/dsa.veil.v1.VeilCertificateService/VerifyCertificate"
)

// VeilCertificateServiceClient is the client API for VeilCertificateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VeilCertificateService is the canonical witness surface the dashboard
// consumes for cert lookup + verification. Method names + signatures
// match upstream EXACTLY; any drift is caught by the Go-level
// TestVerify_RealUpstreamServiceShape regression test.
type VeilCertificateServiceClient interface {
	GetCertificate(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*VeilCertificate, error)
	ExportCertificates(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VeilCertificate], error)
	VerifyCertificate(ctx context.Context, in *VeilCertificate, opts ...grpc.CallOption) (*VerificationResult, error)
}

type veilCertificateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVeilCertificateServiceClient(cc grpc.ClientConnInterface) VeilCertificateServiceClient {
	return &veilCertificateServiceClient{cc}
}

func (c *veilCertificateServiceClient) GetCertificate(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*VeilCertificate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VeilCertificate)
	err := c.cc.Invoke(ctx, VeilCertificateService_GetCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *veilCertificateServiceClient) ExportCertificates(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VeilCertificate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VeilCertificateService_ServiceDesc.Streams[0], VeilCertificateService_ExportCertificates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportRequest, VeilCertificate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VeilCertificateService_ExportCertificatesClient = grpc.ServerStreamingClient[VeilCertificate]

func (c *veilCertificateServiceClient) VerifyCertificate(ctx context.Context, in *VeilCertificate, opts ...grpc.CallOption) (*VerificationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerificationResult)
	err := c.cc.Invoke(ctx, VeilCertificateService_VerifyCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VeilCertificateServiceServer is the server API for VeilCertificateService service.
// All implementations must embed UnimplementedVeilCertificateServiceServer
// for forward compatibility.
//
// VeilCertificateService is the canonical witness surface the dashboard
// consumes for cert lookup + verification. Method names + signatures
// match upstream EXACTLY; any drift is caught by the Go-level
// TestVerify_RealUpstreamServiceShape regression test.
type VeilCertificateServiceServer interface {
	GetCertificate(context.Context, *GetCertificateRequest) (*VeilCertificate, error)
	ExportCertificates(*ExportRequest, grpc.ServerStreamingServer[VeilCertificate]) error
	VerifyCertificate(context.Context, *VeilCertificate) (*VerificationResult, error)
	mustEmbedUnimplementedVeilCertificateServiceServer()
}

// UnimplementedVeilCertificateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVeilCertificateServiceServer struct{}

func (UnimplementedVeilCertificateServiceServer) GetCertificate(context.Context, *GetCertificateRequest) (*VeilCertificate, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCertificate not implemented")
}
func (UnimplementedVeilCertificateServiceServer) ExportCertificates(*ExportRequest, grpc.ServerStreamingServer[VeilCertificate]) error {
	return status.Error(codes.Unimplemented, "method ExportCertificates not implemented")
}
func (UnimplementedVeilCertificateServiceServer) VerifyCertificate(context.Context, *VeilCertificate) (*VerificationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyCertificate not implemented")
}
func (UnimplementedVeilCertificateServiceServer) mustEmbedUnimplementedVeilCertificateServiceServer() {
}
func (UnimplementedVeilCertificateServiceServer) testEmbeddedByValue() {}

// UnsafeVeilCertificateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VeilCertificateServiceServer will
// result in compilation errors.
type UnsafeVeilCertificateServiceServer interface {
	mustEmbedUnimplementedVeilCertificateServiceServer()
}

func RegisterVeilCertificateServiceServer(s grpc.ServiceRegistrar, srv VeilCertificateServiceServer) {
	// If the following call panics, it indicates UnimplementedVeilCertificateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VeilCertificateService_ServiceDesc, srv)
}

func _VeilCertificateService_GetCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VeilCertificateServiceServer).GetCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VeilCertificateService_GetCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VeilCertificateServiceServer).GetCertificate(ctx, req.(*GetCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VeilCertificateService_ExportCertificates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VeilCertificateServiceServer).ExportCertificates(m, &grpc.GenericServerStream[ExportRequest, VeilCertificate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VeilCertificateService_ExportCertificatesServer = grpc.ServerStreamingServer[VeilCertificate]

func _VeilCertificateService_VerifyCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VeilCertificate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VeilCertificateServiceServer).VerifyCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VeilCertificateService_VerifyCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VeilCertificateServiceServer).VerifyCertificate(ctx, req.(*VeilCertificate))
	}
	return interceptor(ctx, in, info, handler)
}

// VeilCertificateService_ServiceDesc is the grpc.ServiceDesc for VeilCertificateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VeilCertificateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dsa.veil.v1.VeilCertificateService",
	HandlerType: (*VeilCertificateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCertificate",
			Handler:    _VeilCertificateService_GetCertificate_Handler,
		},
		{
			MethodName: "VerifyCertificate",
			Handler:    _VeilCertificateService_VerifyCertificate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportCertificates",
			Handler:       _VeilCertificateService_ExportCertificates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "witness.proto",
}
