// Vendored from Declade/dual-sandbox-architecture:
//   proto/veil/v1/veil.proto @ commit f24bf0d2565ff5d414c0ee13c3188675d8f67d3c
// + proto/common/v1/types.proto (only EntityCount inlined, for SanitizerClaim).
//
// This file is the CANONICAL upstream `dsa.veil.v1` schema, vendored
// verbatim so the dashboard speaks the real witness gRPC contract:
//   service VeilCertificateService { GetCertificate, VerifyCertificate, ... }
// NOT the previous (invented) `lucairn.witness.v1.CertVerifier` shape,
// which empirically returned codes.Unimplemented against a real witness.
//
// KEEP IN SYNC: when the upstream proto field numbers or message names
// change, regenerate via:
//   make -C apps/dashboard proto-sync
// (or directly:)
//   protoc --proto_path=internal/witness \
//     --go_out=internal/witness/pb --go_opt=paths=source_relative \
//     --go-grpc_out=internal/witness/pb --go-grpc_opt=paths=source_relative \
//     internal/witness/witness.proto
//
// The contract-drift-detector subagent runs against every Slice-touching
// PR; expect it to flag any drift between this vendored copy and upstream.
// The Go-level regression test TestVerify_RealUpstreamServiceShape
// (verify_client_test.go) locks the fully-qualified method names dialed
// so a future copy-paste typo in this file is caught at unit-test time.
//
// Cross-language byte equality with the witness service is REQUIRED —
// the witness reconstructs the per-claim canonical bytes from THIS schema
// when it Verifies; we don't canonicalize anything on the dashboard side
// (we just round-trip the envelope). Field numbers, enum values, oneof
// tags MUST remain IDENTICAL to upstream.
//
// Out of scope here: VeilWitnessService.SubmitClaim — that RPC is the
// per-service emit path; the dashboard never calls it. It is intentionally
// omitted from this vendored copy. If the upstream witness ever adds a
// dashboard-facing RPC under VeilWitnessService, regenerate this file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: witness.proto

package witnesspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimType int32

const (
	ClaimType_CLAIM_TYPE_UNSPECIFIED         ClaimType = 0
	ClaimType_CLAIM_TYPE_TOKEN_GENERATED     ClaimType = 1
	ClaimType_CLAIM_TYPE_PII_SANITIZED       ClaimType = 2
	ClaimType_CLAIM_TYPE_INFERENCE_COMPLETED ClaimType = 3
	ClaimType_CLAIM_TYPE_EVENTS_RECORDED     ClaimType = 4
)

// Enum value maps for ClaimType.
var (
	ClaimType_name = map[int32]string{
		0: "CLAIM_TYPE_UNSPECIFIED",
		1: "CLAIM_TYPE_TOKEN_GENERATED",
		2: "CLAIM_TYPE_PII_SANITIZED",
		3: "CLAIM_TYPE_INFERENCE_COMPLETED",
		4: "CLAIM_TYPE_EVENTS_RECORDED",
	}
	ClaimType_value = map[string]int32{
		"CLAIM_TYPE_UNSPECIFIED":         0,
		"CLAIM_TYPE_TOKEN_GENERATED":     1,
		"CLAIM_TYPE_PII_SANITIZED":       2,
		"CLAIM_TYPE_INFERENCE_COMPLETED": 3,
		"CLAIM_TYPE_EVENTS_RECORDED":     4,
	}
)

func (x ClaimType) Enum() *ClaimType {
	p := new(ClaimType)
	*p = x
	return p
}

func (x ClaimType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClaimType) Descriptor() protoreflect.EnumDescriptor {
	return file_witness_proto_enumTypes[0].Descriptor()
}

func (ClaimType) Type() protoreflect.EnumType {
	return &file_witness_proto_enumTypes[0]
}

func (x ClaimType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClaimType.Descriptor instead.
func (ClaimType) EnumDescriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{0}
}

type IsolationProbeStatus int32

const (
	IsolationProbeStatus_ISOLATION_PROBE_UNKNOWN  IsolationProbeStatus = 0
	IsolationProbeStatus_ISOLATION_PROBE_VERIFIED IsolationProbeStatus = 1
	IsolationProbeStatus_ISOLATION_PROBE_BREACHED IsolationProbeStatus = 2
	IsolationProbeStatus_ISOLATION_PROBE_LOCKED   IsolationProbeStatus = 3
	// BYOK_EXEMPT means the gateway routed inference to a customer-supplied
	// upstream provider (BYOK / `X-Upstream-Key`). Sandbox B did not perform
	// isolated inference for this run; the isolation invariant is therefore
	// intentionally inapplicable rather than violated. The verifier treats
	// this as VERIFIED-equivalent for the overall verdict, with a separate
	// VerificationResult.byok_exempt = true flag so consumers can render
	// "VERIFIED (BYOK exempt)" cleanly.
	IsolationProbeStatus_ISOLATION_PROBE_BYOK_EXEMPT IsolationProbeStatus = 4
)

// Enum value maps for IsolationProbeStatus.
var (
	IsolationProbeStatus_name = map[int32]string{
		0: "ISOLATION_PROBE_UNKNOWN",
		1: "ISOLATION_PROBE_VERIFIED",
		2: "ISOLATION_PROBE_BREACHED",
		3: "ISOLATION_PROBE_LOCKED",
		4: "ISOLATION_PROBE_BYOK_EXEMPT",
	}
	IsolationProbeStatus_value = map[string]int32{
		"ISOLATION_PROBE_UNKNOWN":     0,
		"ISOLATION_PROBE_VERIFIED":    1,
		"ISOLATION_PROBE_BREACHED":    2,
		"ISOLATION_PROBE_LOCKED":      3,
		"ISOLATION_PROBE_BYOK_EXEMPT": 4,
	}
)

func (x IsolationProbeStatus) Enum() *IsolationProbeStatus {
	p := new(IsolationProbeStatus)
	*p = x
	return p
}

func (x IsolationProbeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IsolationProbeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_witness_proto_enumTypes[1].Descriptor()
}

func (IsolationProbeStatus) Type() protoreflect.EnumType {
	return &file_witness_proto_enumTypes[1]
}

func (x IsolationProbeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IsolationProbeStatus.Descriptor instead.
func (IsolationProbeStatus) EnumDescriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{1}
}

type QIVerdict int32

const (
	QIVerdict_QI_VERDICT_UNKNOWN     QIVerdict = 0
	QIVerdict_QI_VERDICT_PASS        QIVerdict = 1
	QIVerdict_QI_VERDICT_GENERALIZED QIVerdict = 2
	QIVerdict_QI_VERDICT_BLOCKED     QIVerdict = 3
)

// Enum value maps for QIVerdict.
var (
	QIVerdict_name = map[int32]string{
		0: "QI_VERDICT_UNKNOWN",
		1: "QI_VERDICT_PASS",
		2: "QI_VERDICT_GENERALIZED",
		3: "QI_VERDICT_BLOCKED",
	}
	QIVerdict_value = map[string]int32{
		"QI_VERDICT_UNKNOWN":     0,
		"QI_VERDICT_PASS":        1,
		"QI_VERDICT_GENERALIZED": 2,
		"QI_VERDICT_BLOCKED":     3,
	}
)

func (x QIVerdict) Enum() *QIVerdict {
	p := new(QIVerdict)
	*p = x
	return p
}

func (x QIVerdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QIVerdict) Descriptor() protoreflect.EnumDescriptor {
	return file_witness_proto_enumTypes[2].Descriptor()
}

func (QIVerdict) Type() protoreflect.EnumType {
	return &file_witness_proto_enumTypes[2]
}

func (x QIVerdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QIVerdict.Descriptor instead.
func (QIVerdict) EnumDescriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{2}
}

type Completeness int32

const (
	Completeness_COMPLETENESS_UNSPECIFIED Completeness = 0
	Completeness_COMPLETENESS_FULL        Completeness = 1
	Completeness_COMPLETENESS_PARTIAL     Completeness = 2
)

// Enum value maps for Completeness.
var (
	Completeness_name = map[int32]string{
		0: "COMPLETENESS_UNSPECIFIED",
		1: "COMPLETENESS_FULL",
		2: "COMPLETENESS_PARTIAL",
	}
	Completeness_value = map[string]int32{
		"COMPLETENESS_UNSPECIFIED": 0,
		"COMPLETENESS_FULL":        1,
		"COMPLETENESS_PARTIAL":     2,
	}
)

func (x Completeness) Enum() *Completeness {
	p := new(Completeness)
	*p = x
	return p
}

func (x Completeness) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Completeness) Descriptor() protoreflect.EnumDescriptor {
	return file_witness_proto_enumTypes[3].Descriptor()
}

func (Completeness) Type() protoreflect.EnumType {
	return &file_witness_proto_enumTypes[3]
}

func (x Completeness) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Completeness.Descriptor instead.
func (Completeness) EnumDescriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{3}
}

type Verdict int32

const (
	Verdict_VERDICT_UNSPECIFIED Verdict = 0
	Verdict_VERDICT_VERIFIED    Verdict = 1
	Verdict_VERDICT_PARTIAL     Verdict = 2
	Verdict_VERDICT_FAILED      Verdict = 3
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "VERDICT_VERIFIED",
		2: "VERDICT_PARTIAL",
		3: "VERDICT_FAILED",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED": 0,
		"VERDICT_VERIFIED":    1,
		"VERDICT_PARTIAL":     2,
		"VERDICT_FAILED":      3,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_witness_proto_enumTypes[4].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_witness_proto_enumTypes[4]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{4}
}

// CC-017 P3: async transparency-log anchor state. A certificate is always
// written and signed immediately; the attestor retry loop then transitions
// the record from PENDING_ANCHOR to either ANCHORED or ANCHOR_FAILED.
// Consumers must render ANCHOR_FAILED alongside anchor_human_note so that
// operators see the signed record is valid but the external anchor did not
// confirm.
type AnchorStatus int32

const (
	AnchorStatus_ANCHOR_STATUS_UNSPECIFIED AnchorStatus = 0
	AnchorStatus_ANCHOR_STATUS_PENDING     AnchorStatus = 1
	AnchorStatus_ANCHOR_STATUS_ANCHORED    AnchorStatus = 2
	AnchorStatus_ANCHOR_STATUS_FAILED      AnchorStatus = 3
)

// Enum value maps for AnchorStatus.
var (
	AnchorStatus_name = map[int32]string{
		0: "ANCHOR_STATUS_UNSPECIFIED",
		1: "ANCHOR_STATUS_PENDING",
		2: "ANCHOR_STATUS_ANCHORED",
		3: "ANCHOR_STATUS_FAILED",
	}
	AnchorStatus_value = map[string]int32{
		"ANCHOR_STATUS_UNSPECIFIED": 0,
		"ANCHOR_STATUS_PENDING":     1,
		"ANCHOR_STATUS_ANCHORED":    2,
		"ANCHOR_STATUS_FAILED":      3,
	}
)

func (x AnchorStatus) Enum() *AnchorStatus {
	p := new(AnchorStatus)
	*p = x
	return p
}

func (x AnchorStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnchorStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_witness_proto_enumTypes[5].Descriptor()
}

func (AnchorStatus) Type() protoreflect.EnumType {
	return &file_witness_proto_enumTypes[5]
}

func (x AnchorStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnchorStatus.Descriptor instead.
func (AnchorStatus) EnumDescriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{5}
}

// EntityCount represents a per-type PII entity count.
// Shared between audit and veil protos. Inlined here under the local
// `dsa.veil.v1` package so this proto file is self-contained — the
// upstream definition lives in `dsa.common.v1`, but mirroring just this
// one message (vs vendoring the entire common types proto) keeps the
// dashboard's vendored surface minimal.
type EntityCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityCount) Reset() {
	*x = EntityCount{}
	mi := &file_witness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityCount) ProtoMessage() {}

func (x *EntityCount) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityCount.ProtoReflect.Descriptor instead.
func (*EntityCount) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{0}
}

func (x *EntityCount) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EntityCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type VeilClaim struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClaimId          string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	RequestId        string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ServiceId        string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ClaimType        ClaimType              `protobuf:"varint,4,opt,name=claim_type,json=claimType,proto3,enum=dsa.veil.v1.ClaimType" json:"claim_type,omitempty"`
	DataSeen         []string               `protobuf:"bytes,5,rep,name=data_seen,json=dataSeen,proto3" json:"data_seen,omitempty"`
	DataNotSeen      []string               `protobuf:"bytes,6,rep,name=data_not_seen,json=dataNotSeen,proto3" json:"data_not_seen,omitempty"`
	CanonicalPayload []byte                 `protobuf:"bytes,7,opt,name=canonical_payload,json=canonicalPayload,proto3" json:"canonical_payload,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*VeilClaim_Bridge
	//	*VeilClaim_Sanitizer
	//	*VeilClaim_Inference
	//	*VeilClaim_Audit
	Payload       isVeilClaim_Payload    `protobuf_oneof:"payload"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     []byte                 `protobuf:"bytes,15,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VeilClaim) Reset() {
	*x = VeilClaim{}
	mi := &file_witness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VeilClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VeilClaim) ProtoMessage() {}

func (x *VeilClaim) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VeilClaim.ProtoReflect.Descriptor instead.
func (*VeilClaim) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{1}
}

func (x *VeilClaim) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *VeilClaim) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *VeilClaim) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *VeilClaim) GetClaimType() ClaimType {
	if x != nil {
		return x.ClaimType
	}
	return ClaimType_CLAIM_TYPE_UNSPECIFIED
}

func (x *VeilClaim) GetDataSeen() []string {
	if x != nil {
		return x.DataSeen
	}
	return nil
}

func (x *VeilClaim) GetDataNotSeen() []string {
	if x != nil {
		return x.DataNotSeen
	}
	return nil
}

func (x *VeilClaim) GetCanonicalPayload() []byte {
	if x != nil {
		return x.CanonicalPayload
	}
	return nil
}

func (x *VeilClaim) GetPayload() isVeilClaim_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VeilClaim) GetBridge() *BridgeClaim {
	if x != nil {
		if x, ok := x.Payload.(*VeilClaim_Bridge); ok {
			return x.Bridge
		}
	}
	return nil
}

func (x *VeilClaim) GetSanitizer() *SanitizerClaim {
	if x != nil {
		if x, ok := x.Payload.(*VeilClaim_Sanitizer); ok {
			return x.Sanitizer
		}
	}
	return nil
}

func (x *VeilClaim) GetInference() *InferenceClaim {
	if x != nil {
		if x, ok := x.Payload.(*VeilClaim_Inference); ok {
			return x.Inference
		}
	}
	return nil
}

func (x *VeilClaim) GetAudit() *AuditClaim {
	if x != nil {
		if x, ok := x.Payload.(*VeilClaim_Audit); ok {
			return x.Audit
		}
	}
	return nil
}

func (x *VeilClaim) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *VeilClaim) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type isVeilClaim_Payload interface {
	isVeilClaim_Payload()
}

type VeilClaim_Bridge struct {
	Bridge *BridgeClaim `protobuf:"bytes,10,opt,name=bridge,proto3,oneof"`
}

type VeilClaim_Sanitizer struct {
	Sanitizer *SanitizerClaim `protobuf:"bytes,11,opt,name=sanitizer,proto3,oneof"`
}

type VeilClaim_Inference struct {
	Inference *InferenceClaim `protobuf:"bytes,12,opt,name=inference,proto3,oneof"`
}

type VeilClaim_Audit struct {
	Audit *AuditClaim `protobuf:"bytes,13,opt,name=audit,proto3,oneof"`
}

func (*VeilClaim_Bridge) isVeilClaim_Payload() {}

func (*VeilClaim_Sanitizer) isVeilClaim_Payload() {}

func (*VeilClaim_Inference) isVeilClaim_Payload() {}

func (*VeilClaim_Audit) isVeilClaim_Payload() {}

type BridgeClaim struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TokenHash         []byte                 `protobuf:"bytes,1,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	Epoch             uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	EncryptionEnabled bool                   `protobuf:"varint,3,opt,name=encryption_enabled,json=encryptionEnabled,proto3" json:"encryption_enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BridgeClaim) Reset() {
	*x = BridgeClaim{}
	mi := &file_witness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeClaim) ProtoMessage() {}

func (x *BridgeClaim) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeClaim.ProtoReflect.Descriptor instead.
func (*BridgeClaim) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{2}
}

func (x *BridgeClaim) GetTokenHash() []byte {
	if x != nil {
		return x.TokenHash
	}
	return nil
}

func (x *BridgeClaim) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *BridgeClaim) GetEncryptionEnabled() bool {
	if x != nil {
		return x.EncryptionEnabled
	}
	return false
}

type SanitizerClaim struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PiiEntitiesFound      uint32                 `protobuf:"varint,1,opt,name=pii_entities_found,json=piiEntitiesFound,proto3" json:"pii_entities_found,omitempty"`
	RedactionManifestHash []byte                 `protobuf:"bytes,2,opt,name=redaction_manifest_hash,json=redactionManifestHash,proto3" json:"redaction_manifest_hash,omitempty"`
	LayersActive          []string               `protobuf:"bytes,3,rep,name=layers_active,json=layersActive,proto3" json:"layers_active,omitempty"`
	QiScore               *QIScore               `protobuf:"bytes,4,opt,name=qi_score,json=qiScore,proto3" json:"qi_score,omitempty"`
	// Field number kept identical to upstream `dsa.common.v1.EntityCount`
	// reference. Wire-format is independent of the type-name as long as the
	// tag + on-the-wire shape matches.
	EntityCounts        []*EntityCount `protobuf:"bytes,5,rep,name=entity_counts,json=entityCounts,proto3" json:"entity_counts,omitempty"`
	SanitizationSummary string         `protobuf:"bytes,6,opt,name=sanitization_summary,json=sanitizationSummary,proto3" json:"sanitization_summary,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SanitizerClaim) Reset() {
	*x = SanitizerClaim{}
	mi := &file_witness_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizerClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizerClaim) ProtoMessage() {}

func (x *SanitizerClaim) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizerClaim.ProtoReflect.Descriptor instead.
func (*SanitizerClaim) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{3}
}

func (x *SanitizerClaim) GetPiiEntitiesFound() uint32 {
	if x != nil {
		return x.PiiEntitiesFound
	}
	return 0
}

func (x *SanitizerClaim) GetRedactionManifestHash() []byte {
	if x != nil {
		return x.RedactionManifestHash
	}
	return nil
}

func (x *SanitizerClaim) GetLayersActive() []string {
	if x != nil {
		return x.LayersActive
	}
	return nil
}

func (x *SanitizerClaim) GetQiScore() *QIScore {
	if x != nil {
		return x.QiScore
	}
	return nil
}

func (x *SanitizerClaim) GetEntityCounts() []*EntityCount {
	if x != nil {
		return x.EntityCounts
	}
	return nil
}

func (x *SanitizerClaim) GetSanitizationSummary() string {
	if x != nil {
		return x.SanitizationSummary
	}
	return ""
}

type QIScore struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	KAnonymity        uint32                 `protobuf:"varint,1,opt,name=k_anonymity,json=kAnonymity,proto3" json:"k_anonymity,omitempty"`
	LDiversity        float32                `protobuf:"fixed32,2,opt,name=l_diversity,json=lDiversity,proto3" json:"l_diversity,omitempty"`
	RiskScore         float32                `protobuf:"fixed32,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Threshold         float32                `protobuf:"fixed32,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Verdict           QIVerdict              `protobuf:"varint,5,opt,name=verdict,proto3,enum=dsa.veil.v1.QIVerdict" json:"verdict,omitempty"`
	FieldsGeneralized []string               `protobuf:"bytes,6,rep,name=fields_generalized,json=fieldsGeneralized,proto3" json:"fields_generalized,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QIScore) Reset() {
	*x = QIScore{}
	mi := &file_witness_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QIScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QIScore) ProtoMessage() {}

func (x *QIScore) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QIScore.ProtoReflect.Descriptor instead.
func (*QIScore) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{4}
}

func (x *QIScore) GetKAnonymity() uint32 {
	if x != nil {
		return x.KAnonymity
	}
	return 0
}

func (x *QIScore) GetLDiversity() float32 {
	if x != nil {
		return x.LDiversity
	}
	return 0
}

func (x *QIScore) GetRiskScore() float32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *QIScore) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *QIScore) GetVerdict() QIVerdict {
	if x != nil {
		return x.Verdict
	}
	return QIVerdict_QI_VERDICT_UNKNOWN
}

func (x *QIScore) GetFieldsGeneralized() []string {
	if x != nil {
		return x.FieldsGeneralized
	}
	return nil
}

type InferenceClaim struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsolationProbe IsolationProbeStatus   `protobuf:"varint,1,opt,name=isolation_probe,json=isolationProbe,proto3,enum=dsa.veil.v1.IsolationProbeStatus" json:"isolation_probe,omitempty"`
	ModelUsed      string                 `protobuf:"bytes,2,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	ResponseHash   []byte                 `protobuf:"bytes,3,opt,name=response_hash,json=responseHash,proto3" json:"response_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InferenceClaim) Reset() {
	*x = InferenceClaim{}
	mi := &file_witness_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceClaim) ProtoMessage() {}

func (x *InferenceClaim) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceClaim.ProtoReflect.Descriptor instead.
func (*InferenceClaim) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{5}
}

func (x *InferenceClaim) GetIsolationProbe() IsolationProbeStatus {
	if x != nil {
		return x.IsolationProbe
	}
	return IsolationProbeStatus_ISOLATION_PROBE_UNKNOWN
}

func (x *InferenceClaim) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *InferenceClaim) GetResponseHash() []byte {
	if x != nil {
		return x.ResponseHash
	}
	return nil
}

type AuditClaim struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventIds          []string               `protobuf:"bytes,1,rep,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	ChainHeadHash     []byte                 `protobuf:"bytes,2,opt,name=chain_head_hash,json=chainHeadHash,proto3" json:"chain_head_hash,omitempty"`
	PreviousChainHash []byte                 `protobuf:"bytes,3,opt,name=previous_chain_hash,json=previousChainHash,proto3" json:"previous_chain_hash,omitempty"`
	ChainLength       uint64                 `protobuf:"varint,4,opt,name=chain_length,json=chainLength,proto3" json:"chain_length,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuditClaim) Reset() {
	*x = AuditClaim{}
	mi := &file_witness_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditClaim) ProtoMessage() {}

func (x *AuditClaim) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditClaim.ProtoReflect.Descriptor instead.
func (*AuditClaim) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{6}
}

func (x *AuditClaim) GetEventIds() []string {
	if x != nil {
		return x.EventIds
	}
	return nil
}

func (x *AuditClaim) GetChainHeadHash() []byte {
	if x != nil {
		return x.ChainHeadHash
	}
	return nil
}

func (x *AuditClaim) GetPreviousChainHash() []byte {
	if x != nil {
		return x.PreviousChainHash
	}
	return nil
}

func (x *AuditClaim) GetChainLength() uint64 {
	if x != nil {
		return x.ChainLength
	}
	return 0
}

type VeilCertificate struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CertificateId      string                 `protobuf:"bytes,1,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	RequestId          string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ProtocolVersion    uint32                 `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Claims             []*VeilClaim           `protobuf:"bytes,4,rep,name=claims,proto3" json:"claims,omitempty"`
	Verification       *VerificationResult    `protobuf:"bytes,5,opt,name=verification,proto3" json:"verification,omitempty"`
	WitnessSignature   []byte                 `protobuf:"bytes,6,opt,name=witness_signature,json=witnessSignature,proto3" json:"witness_signature,omitempty"`
	WitnessKeyId       string                 `protobuf:"bytes,7,opt,name=witness_key_id,json=witnessKeyId,proto3" json:"witness_key_id,omitempty"`
	Attestation        *ExternalAttestation   `protobuf:"bytes,8,opt,name=attestation,proto3" json:"attestation,omitempty"`
	IssuedAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	FormalVerification *FormalVerification    `protobuf:"bytes,10,opt,name=formal_verification,json=formalVerification,proto3" json:"formal_verification,omitempty"`
	AuditIntegrity     *AuditIntegrity        `protobuf:"bytes,11,opt,name=audit_integrity,json=auditIntegrity,proto3" json:"audit_integrity,omitempty"`
	PrivacyBudget      *PrivacyBudget         `protobuf:"bytes,12,opt,name=privacy_budget,json=privacyBudget,proto3" json:"privacy_budget,omitempty"`
	// CC-017 P3: async transparency-log anchor state exposed on export and
	// lookup. The cryptographic signature over core certificate fields is
	// always valid; the fields below only describe whether the external
	// TSA/Rekor anchor confirmed within the retry window.
	AnchorStatus *AnchorStatusInfo `protobuf:"bytes,13,opt,name=anchor_status,json=anchorStatus,proto3" json:"anchor_status,omitempty"`
	// client_id is the org_id metadata for client-side correlation. NOT
	// covered by the witness signable; NOT tamper-evident at this layer.
	// Tamper-evidence is INDIRECT: org_id is also carried in the bridge
	// claim's canonical_payload (which IS bridge-signed and is part of the
	// witness signable via `claims`). Cross-checking customer can correlate
	// cert.client_id against the bridge claim payload's org_id (defense-in-
	// depth, optional). Promote to signable in the future SDK signable-
	// versioning workstream.
	ClientId      *string `protobuf:"bytes,14,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VeilCertificate) Reset() {
	*x = VeilCertificate{}
	mi := &file_witness_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VeilCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VeilCertificate) ProtoMessage() {}

func (x *VeilCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VeilCertificate.ProtoReflect.Descriptor instead.
func (*VeilCertificate) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{7}
}

func (x *VeilCertificate) GetCertificateId() string {
	if x != nil {
		return x.CertificateId
	}
	return ""
}

func (x *VeilCertificate) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *VeilCertificate) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *VeilCertificate) GetClaims() []*VeilClaim {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *VeilCertificate) GetVerification() *VerificationResult {
	if x != nil {
		return x.Verification
	}
	return nil
}

func (x *VeilCertificate) GetWitnessSignature() []byte {
	if x != nil {
		return x.WitnessSignature
	}
	return nil
}

func (x *VeilCertificate) GetWitnessKeyId() string {
	if x != nil {
		return x.WitnessKeyId
	}
	return ""
}

func (x *VeilCertificate) GetAttestation() *ExternalAttestation {
	if x != nil {
		return x.Attestation
	}
	return nil
}

func (x *VeilCertificate) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *VeilCertificate) GetFormalVerification() *FormalVerification {
	if x != nil {
		return x.FormalVerification
	}
	return nil
}

func (x *VeilCertificate) GetAuditIntegrity() *AuditIntegrity {
	if x != nil {
		return x.AuditIntegrity
	}
	return nil
}

func (x *VeilCertificate) GetPrivacyBudget() *PrivacyBudget {
	if x != nil {
		return x.PrivacyBudget
	}
	return nil
}

func (x *VeilCertificate) GetAnchorStatus() *AnchorStatusInfo {
	if x != nil {
		return x.AnchorStatus
	}
	return nil
}

func (x *VeilCertificate) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

type AnchorStatusInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Status    AnchorStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=dsa.veil.v1.AnchorStatus" json:"status,omitempty"`
	Attempts  uint32                 `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	LastError string                 `protobuf:"bytes,3,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// Human-readable operator note. Populated on ANCHOR_FAILED with the exact
	// text consumers must render next to the certificate so operators see
	// that the signed record is valid but the external anchor could not be
	// confirmed.
	HumanNote     string `protobuf:"bytes,4,opt,name=human_note,json=humanNote,proto3" json:"human_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorStatusInfo) Reset() {
	*x = AnchorStatusInfo{}
	mi := &file_witness_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorStatusInfo) ProtoMessage() {}

func (x *AnchorStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorStatusInfo.ProtoReflect.Descriptor instead.
func (*AnchorStatusInfo) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{8}
}

func (x *AnchorStatusInfo) GetStatus() AnchorStatus {
	if x != nil {
		return x.Status
	}
	return AnchorStatus_ANCHOR_STATUS_UNSPECIFIED
}

func (x *AnchorStatusInfo) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *AnchorStatusInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *AnchorStatusInfo) GetHumanNote() string {
	if x != nil {
		return x.HumanNote
	}
	return ""
}

type VerificationResult struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SignaturesValid          bool                   `protobuf:"varint,1,opt,name=signatures_valid,json=signaturesValid,proto3" json:"signatures_valid,omitempty"`
	Completeness             Completeness           `protobuf:"varint,2,opt,name=completeness,proto3,enum=dsa.veil.v1.Completeness" json:"completeness,omitempty"`
	MissingServices          []string               `protobuf:"bytes,3,rep,name=missing_services,json=missingServices,proto3" json:"missing_services,omitempty"`
	TemporalConsistent       bool                   `protobuf:"varint,4,opt,name=temporal_consistent,json=temporalConsistent,proto3" json:"temporal_consistent,omitempty"`
	DataVisibilityConsistent bool                   `protobuf:"varint,5,opt,name=data_visibility_consistent,json=dataVisibilityConsistent,proto3" json:"data_visibility_consistent,omitempty"`
	IsolationVerified        bool                   `protobuf:"varint,6,opt,name=isolation_verified,json=isolationVerified,proto3" json:"isolation_verified,omitempty"`
	QiScore                  *QIScore               `protobuf:"bytes,7,opt,name=qi_score,json=qiScore,proto3" json:"qi_score,omitempty"`
	OverallVerdict           Verdict                `protobuf:"varint,8,opt,name=overall_verdict,json=overallVerdict,proto3,enum=dsa.veil.v1.Verdict" json:"overall_verdict,omitempty"`
	// BYOK exemption: true when at least one dsa-ai claim in the chain
	// carried IsolationProbe = ISOLATION_PROBE_BYOK_EXEMPT, indicating the
	// gateway routed inference to a customer-supplied upstream provider.
	// When true, isolation_verified is set true (BYOK_EXEMPT is accepted as
	// VERIFIED-equivalent for the overall verdict) and the cert is safe to
	// render as VERIFIED. Consumers SHOULD render a "BYOK exempt" badge
	// alongside the verified state. Older verifiers without this field
	// still see overall_verdict = VERIFIED and isolation_verified = true.
	ByokExempt    bool `protobuf:"varint,9,opt,name=byok_exempt,json=byokExempt,proto3" json:"byok_exempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationResult) Reset() {
	*x = VerificationResult{}
	mi := &file_witness_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResult) ProtoMessage() {}

func (x *VerificationResult) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResult.ProtoReflect.Descriptor instead.
func (*VerificationResult) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{9}
}

func (x *VerificationResult) GetSignaturesValid() bool {
	if x != nil {
		return x.SignaturesValid
	}
	return false
}

func (x *VerificationResult) GetCompleteness() Completeness {
	if x != nil {
		return x.Completeness
	}
	return Completeness_COMPLETENESS_UNSPECIFIED
}

func (x *VerificationResult) GetMissingServices() []string {
	if x != nil {
		return x.MissingServices
	}
	return nil
}

func (x *VerificationResult) GetTemporalConsistent() bool {
	if x != nil {
		return x.TemporalConsistent
	}
	return false
}

func (x *VerificationResult) GetDataVisibilityConsistent() bool {
	if x != nil {
		return x.DataVisibilityConsistent
	}
	return false
}

func (x *VerificationResult) GetIsolationVerified() bool {
	if x != nil {
		return x.IsolationVerified
	}
	return false
}

func (x *VerificationResult) GetQiScore() *QIScore {
	if x != nil {
		return x.QiScore
	}
	return nil
}

func (x *VerificationResult) GetOverallVerdict() Verdict {
	if x != nil {
		return x.OverallVerdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *VerificationResult) GetByokExempt() bool {
	if x != nil {
		return x.ByokExempt
	}
	return false
}

type ExternalAttestation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       *TimestampAttestation  `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TransparencyLog *TransparencyLogEntry  `protobuf:"bytes,2,opt,name=transparency_log,json=transparencyLog,proto3" json:"transparency_log,omitempty"`
	Notary          *NotaryAttestation     `protobuf:"bytes,3,opt,name=notary,proto3" json:"notary,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExternalAttestation) Reset() {
	*x = ExternalAttestation{}
	mi := &file_witness_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalAttestation) ProtoMessage() {}

func (x *ExternalAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalAttestation.ProtoReflect.Descriptor instead.
func (*ExternalAttestation) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{10}
}

func (x *ExternalAttestation) GetTimestamp() *TimestampAttestation {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExternalAttestation) GetTransparencyLog() *TransparencyLogEntry {
	if x != nil {
		return x.TransparencyLog
	}
	return nil
}

func (x *ExternalAttestation) GetNotary() *NotaryAttestation {
	if x != nil {
		return x.Notary
	}
	return nil
}

type TimestampAttestation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	TimestampToken []byte                 `protobuf:"bytes,2,opt,name=timestamp_token,json=timestampToken,proto3" json:"timestamp_token,omitempty"`
	CertHash       []byte                 `protobuf:"bytes,3,opt,name=cert_hash,json=certHash,proto3" json:"cert_hash,omitempty"`
	HashAlgorithm  string                 `protobuf:"bytes,4,opt,name=hash_algorithm,json=hashAlgorithm,proto3" json:"hash_algorithm,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TimestampAttestation) Reset() {
	*x = TimestampAttestation{}
	mi := &file_witness_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampAttestation) ProtoMessage() {}

func (x *TimestampAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampAttestation.ProtoReflect.Descriptor instead.
func (*TimestampAttestation) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{11}
}

func (x *TimestampAttestation) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TimestampAttestation) GetTimestampToken() []byte {
	if x != nil {
		return x.TimestampToken
	}
	return nil
}

func (x *TimestampAttestation) GetCertHash() []byte {
	if x != nil {
		return x.CertHash
	}
	return nil
}

func (x *TimestampAttestation) GetHashAlgorithm() string {
	if x != nil {
		return x.HashAlgorithm
	}
	return ""
}

type TransparencyLogEntry struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Provider             string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	LogIndex             int64                  `protobuf:"varint,2,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	InclusionProof       []byte                 `protobuf:"bytes,3,opt,name=inclusion_proof,json=inclusionProof,proto3" json:"inclusion_proof,omitempty"`
	SignedEntryTimestamp []byte                 `protobuf:"bytes,4,opt,name=signed_entry_timestamp,json=signedEntryTimestamp,proto3" json:"signed_entry_timestamp,omitempty"`
	LogUrl               string                 `protobuf:"bytes,5,opt,name=log_url,json=logUrl,proto3" json:"log_url,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TransparencyLogEntry) Reset() {
	*x = TransparencyLogEntry{}
	mi := &file_witness_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransparencyLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransparencyLogEntry) ProtoMessage() {}

func (x *TransparencyLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransparencyLogEntry.ProtoReflect.Descriptor instead.
func (*TransparencyLogEntry) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{12}
}

func (x *TransparencyLogEntry) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TransparencyLogEntry) GetLogIndex() int64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *TransparencyLogEntry) GetInclusionProof() []byte {
	if x != nil {
		return x.InclusionProof
	}
	return nil
}

func (x *TransparencyLogEntry) GetSignedEntryTimestamp() []byte {
	if x != nil {
		return x.SignedEntryTimestamp
	}
	return nil
}

func (x *TransparencyLogEntry) GetLogUrl() string {
	if x != nil {
		return x.LogUrl
	}
	return ""
}

type NotaryAttestation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Provider          string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	NotarySignature   []byte                 `protobuf:"bytes,2,opt,name=notary_signature,json=notarySignature,proto3" json:"notary_signature,omitempty"`
	NotaryPublicKeyId string                 `protobuf:"bytes,3,opt,name=notary_public_key_id,json=notaryPublicKeyId,proto3" json:"notary_public_key_id,omitempty"`
	ChecksPerformed   []string               `protobuf:"bytes,4,rep,name=checks_performed,json=checksPerformed,proto3" json:"checks_performed,omitempty"`
	AttestedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=attested_at,json=attestedAt,proto3" json:"attested_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NotaryAttestation) Reset() {
	*x = NotaryAttestation{}
	mi := &file_witness_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotaryAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotaryAttestation) ProtoMessage() {}

func (x *NotaryAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotaryAttestation.ProtoReflect.Descriptor instead.
func (*NotaryAttestation) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{13}
}

func (x *NotaryAttestation) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *NotaryAttestation) GetNotarySignature() []byte {
	if x != nil {
		return x.NotarySignature
	}
	return nil
}

func (x *NotaryAttestation) GetNotaryPublicKeyId() string {
	if x != nil {
		return x.NotaryPublicKeyId
	}
	return ""
}

func (x *NotaryAttestation) GetChecksPerformed() []string {
	if x != nil {
		return x.ChecksPerformed
	}
	return nil
}

func (x *NotaryAttestation) GetAttestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AttestedAt
	}
	return nil
}

type FormalVerification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecHash      string                 `protobuf:"bytes,1,opt,name=spec_hash,json=specHash,proto3" json:"spec_hash,omitempty"`
	ProofHash     string                 `protobuf:"bytes,2,opt,name=proof_hash,json=proofHash,proto3" json:"proof_hash,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	VerifiedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormalVerification) Reset() {
	*x = FormalVerification{}
	mi := &file_witness_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormalVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormalVerification) ProtoMessage() {}

func (x *FormalVerification) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormalVerification.ProtoReflect.Descriptor instead.
func (*FormalVerification) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{14}
}

func (x *FormalVerification) GetSpecHash() string {
	if x != nil {
		return x.SpecHash
	}
	return ""
}

func (x *FormalVerification) GetProofHash() string {
	if x != nil {
		return x.ProofHash
	}
	return ""
}

func (x *FormalVerification) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *FormalVerification) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

type MerkleInclusionProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeSize      uint64                 `protobuf:"varint,1,opt,name=tree_size,json=treeSize,proto3" json:"tree_size,omitempty"`
	LeafIndex     uint64                 `protobuf:"varint,2,opt,name=leaf_index,json=leafIndex,proto3" json:"leaf_index,omitempty"`
	PathHashes    [][]byte               `protobuf:"bytes,3,rep,name=path_hashes,json=pathHashes,proto3" json:"path_hashes,omitempty"`
	IsRight       []bool                 `protobuf:"varint,4,rep,packed,name=is_right,json=isRight,proto3" json:"is_right,omitempty"`
	RootHash      []byte                 `protobuf:"bytes,5,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	RootSignature []byte                 `protobuf:"bytes,6,opt,name=root_signature,json=rootSignature,proto3" json:"root_signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleInclusionProof) Reset() {
	*x = MerkleInclusionProof{}
	mi := &file_witness_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleInclusionProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleInclusionProof) ProtoMessage() {}

func (x *MerkleInclusionProof) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleInclusionProof.ProtoReflect.Descriptor instead.
func (*MerkleInclusionProof) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{15}
}

func (x *MerkleInclusionProof) GetTreeSize() uint64 {
	if x != nil {
		return x.TreeSize
	}
	return 0
}

func (x *MerkleInclusionProof) GetLeafIndex() uint64 {
	if x != nil {
		return x.LeafIndex
	}
	return 0
}

func (x *MerkleInclusionProof) GetPathHashes() [][]byte {
	if x != nil {
		return x.PathHashes
	}
	return nil
}

func (x *MerkleInclusionProof) GetIsRight() []bool {
	if x != nil {
		return x.IsRight
	}
	return nil
}

func (x *MerkleInclusionProof) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *MerkleInclusionProof) GetRootSignature() []byte {
	if x != nil {
		return x.RootSignature
	}
	return nil
}

type TransparencyLogProof struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LogName        string                 `protobuf:"bytes,1,opt,name=log_name,json=logName,proto3" json:"log_name,omitempty"`
	LogIndex       uint64                 `protobuf:"varint,2,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	InclusionProof []byte                 `protobuf:"bytes,3,opt,name=inclusion_proof,json=inclusionProof,proto3" json:"inclusion_proof,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransparencyLogProof) Reset() {
	*x = TransparencyLogProof{}
	mi := &file_witness_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransparencyLogProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransparencyLogProof) ProtoMessage() {}

func (x *TransparencyLogProof) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransparencyLogProof.ProtoReflect.Descriptor instead.
func (*TransparencyLogProof) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{16}
}

func (x *TransparencyLogProof) GetLogName() string {
	if x != nil {
		return x.LogName
	}
	return ""
}

func (x *TransparencyLogProof) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *TransparencyLogProof) GetInclusionProof() []byte {
	if x != nil {
		return x.InclusionProof
	}
	return nil
}

type AuditIntegrity struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	MerkleRoot     []byte                  `protobuf:"bytes,1,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	TreeSize       uint64                  `protobuf:"varint,2,opt,name=tree_size,json=treeSize,proto3" json:"tree_size,omitempty"`
	InclusionProof *MerkleInclusionProof   `protobuf:"bytes,3,opt,name=inclusion_proof,json=inclusionProof,proto3" json:"inclusion_proof,omitempty"`
	LogProofs      []*TransparencyLogProof `protobuf:"bytes,4,rep,name=log_proofs,json=logProofs,proto3" json:"log_proofs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditIntegrity) Reset() {
	*x = AuditIntegrity{}
	mi := &file_witness_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditIntegrity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditIntegrity) ProtoMessage() {}

func (x *AuditIntegrity) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditIntegrity.ProtoReflect.Descriptor instead.
func (*AuditIntegrity) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{17}
}

func (x *AuditIntegrity) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *AuditIntegrity) GetTreeSize() uint64 {
	if x != nil {
		return x.TreeSize
	}
	return 0
}

func (x *AuditIntegrity) GetInclusionProof() *MerkleInclusionProof {
	if x != nil {
		return x.InclusionProof
	}
	return nil
}

func (x *AuditIntegrity) GetLogProofs() []*TransparencyLogProof {
	if x != nil {
		return x.LogProofs
	}
	return nil
}

type PrivacyBudget struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EpsilonConsumed       float64                `protobuf:"fixed64,1,opt,name=epsilon_consumed,json=epsilonConsumed,proto3" json:"epsilon_consumed,omitempty"`
	EpsilonRemaining      float64                `protobuf:"fixed64,2,opt,name=epsilon_remaining,json=epsilonRemaining,proto3" json:"epsilon_remaining,omitempty"`
	BudgetUtilizationPct  float64                `protobuf:"fixed64,3,opt,name=budget_utilization_pct,json=budgetUtilizationPct,proto3" json:"budget_utilization_pct,omitempty"`
	ReidentificationBound float64                `protobuf:"fixed64,4,opt,name=reidentification_bound,json=reidentificationBound,proto3" json:"reidentification_bound,omitempty"`
	CompositionMethod     string                 `protobuf:"bytes,5,opt,name=composition_method,json=compositionMethod,proto3" json:"composition_method,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PrivacyBudget) Reset() {
	*x = PrivacyBudget{}
	mi := &file_witness_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivacyBudget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacyBudget) ProtoMessage() {}

func (x *PrivacyBudget) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivacyBudget.ProtoReflect.Descriptor instead.
func (*PrivacyBudget) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{18}
}

func (x *PrivacyBudget) GetEpsilonConsumed() float64 {
	if x != nil {
		return x.EpsilonConsumed
	}
	return 0
}

func (x *PrivacyBudget) GetEpsilonRemaining() float64 {
	if x != nil {
		return x.EpsilonRemaining
	}
	return 0
}

func (x *PrivacyBudget) GetBudgetUtilizationPct() float64 {
	if x != nil {
		return x.BudgetUtilizationPct
	}
	return 0
}

func (x *PrivacyBudget) GetReidentificationBound() float64 {
	if x != nil {
		return x.ReidentificationBound
	}
	return 0
}

func (x *PrivacyBudget) GetCompositionMethod() string {
	if x != nil {
		return x.CompositionMethod
	}
	return ""
}

type GetCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WaitTimeout   *durationpb.Duration   `protobuf:"bytes,2,opt,name=wait_timeout,json=waitTimeout,proto3" json:"wait_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateRequest) Reset() {
	*x = GetCertificateRequest{}
	mi := &file_witness_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateRequest) ProtoMessage() {}

func (x *GetCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateRequest) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{19}
}

func (x *GetCertificateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetCertificateRequest) GetWaitTimeout() *durationpb.Duration {
	if x != nil {
		return x.WaitTimeout
	}
	return nil
}

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_witness_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_witness_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_witness_proto_rawDescGZIP(), []int{20}
}

func (x *ExportRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ExportRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ExportRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

var File_witness_proto protoreflect.FileDescriptor

const file_witness_proto_rawDesc = "" +
	"\n" +
	"\rwitness.proto\x12\vdsa.veil.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"D\n" +
	"\vEntityCount\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xcb\x04\n" +
	"\tVeilClaim\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x125\n" +
	"\n" +
	"claim_type\x18\x04 \x01(\x0e2\x16.dsa.veil.v1.ClaimTypeR\tclaimType\x12\x1b\n" +
	"\tdata_seen\x18\x05 \x03(\tR\bdataSeen\x12\"\n" +
	"\rdata_not_seen\x18\x06 \x03(\tR\vdataNotSeen\x12+\n" +
	"\x11canonical_payload\x18\a \x01(\fR\x10canonicalPayload\x122\n" +
	"\x06bridge\x18\n" +
	" \x01(\v2\x18.dsa.veil.v1.BridgeClaimH\x00R\x06bridge\x12;\n" +
	"\tsanitizer\x18\v \x01(\v2\x1b.dsa.veil.v1.SanitizerClaimH\x00R\tsanitizer\x12;\n" +
	"\tinference\x18\f \x01(\v2\x1b.dsa.veil.v1.InferenceClaimH\x00R\tinference\x12/\n" +
	"\x05audit\x18\r \x01(\v2\x17.dsa.veil.v1.AuditClaimH\x00R\x05audit\x128\n" +
	"\ttimestamp\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x0f \x01(\fR\tsignatureB\t\n" +
	"\apayload\"q\n" +
	"\vBridgeClaim\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x01 \x01(\fR\ttokenHash\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12-\n" +
	"\x12encryption_enabled\x18\x03 \x01(\bR\x11encryptionEnabled\"\xbe\x02\n" +
	"\x0eSanitizerClaim\x12,\n" +
	"\x12pii_entities_found\x18\x01 \x01(\rR\x10piiEntitiesFound\x126\n" +
	"\x17redaction_manifest_hash\x18\x02 \x01(\fR\x15redactionManifestHash\x12#\n" +
	"\rlayers_active\x18\x03 \x03(\tR\flayersActive\x12/\n" +
	"\bqi_score\x18\x04 \x01(\v2\x14.dsa.veil.v1.QIScoreR\aqiScore\x12=\n" +
	"\rentity_counts\x18\x05 \x03(\v2\x18.dsa.veil.v1.EntityCountR\fentityCounts\x121\n" +
	"\x14sanitization_summary\x18\x06 \x01(\tR\x13sanitizationSummary\"\xe9\x01\n" +
	"\aQIScore\x12\x1f\n" +
	"\vk_anonymity\x18\x01 \x01(\rR\n" +
	"kAnonymity\x12\x1f\n" +
	"\vl_diversity\x18\x02 \x01(\x02R\n" +
	"lDiversity\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x02R\triskScore\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x02R\tthreshold\x120\n" +
	"\averdict\x18\x05 \x01(\x0e2\x16.dsa.veil.v1.QIVerdictR\averdict\x12-\n" +
	"\x12fields_generalized\x18\x06 \x03(\tR\x11fieldsGeneralized\"\xa0\x01\n" +
	"\x0eInferenceClaim\x12J\n" +
	"\x0fisolation_probe\x18\x01 \x01(\x0e2!.dsa.veil.v1.IsolationProbeStatusR\x0eisolationProbe\x12\x1d\n" +
	"\n" +
	"model_used\x18\x02 \x01(\tR\tmodelUsed\x12#\n" +
	"\rresponse_hash\x18\x03 \x01(\fR\fresponseHash\"\xa4\x01\n" +
	"\n" +
	"AuditClaim\x12\x1b\n" +
	"\tevent_ids\x18\x01 \x03(\tR\beventIds\x12&\n" +
	"\x0fchain_head_hash\x18\x02 \x01(\fR\rchainHeadHash\x12.\n" +
	"\x13previous_chain_hash\x18\x03 \x01(\fR\x11previousChainHash\x12!\n" +
	"\fchain_length\x18\x04 \x01(\x04R\vchainLength\"\x96\x06\n" +
	"\x0fVeilCertificate\x12%\n" +
	"\x0ecertificate_id\x18\x01 \x01(\tR\rcertificateId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\rR\x0fprotocolVersion\x12.\n" +
	"\x06claims\x18\x04 \x03(\v2\x16.dsa.veil.v1.VeilClaimR\x06claims\x12C\n" +
	"\fverification\x18\x05 \x01(\v2\x1f.dsa.veil.v1.VerificationResultR\fverification\x12+\n" +
	"\x11witness_signature\x18\x06 \x01(\fR\x10witnessSignature\x12$\n" +
	"\x0ewitness_key_id\x18\a \x01(\tR\fwitnessKeyId\x12B\n" +
	"\vattestation\x18\b \x01(\v2 .dsa.veil.v1.ExternalAttestationR\vattestation\x127\n" +
	"\tissued_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x12P\n" +
	"\x13formal_verification\x18\n" +
	" \x01(\v2\x1f.dsa.veil.v1.FormalVerificationR\x12formalVerification\x12D\n" +
	"\x0faudit_integrity\x18\v \x01(\v2\x1b.dsa.veil.v1.AuditIntegrityR\x0eauditIntegrity\x12A\n" +
	"\x0eprivacy_budget\x18\f \x01(\v2\x1a.dsa.veil.v1.PrivacyBudgetR\rprivacyBudget\x12B\n" +
	"\ranchor_status\x18\r \x01(\v2\x1d.dsa.veil.v1.AnchorStatusInfoR\fanchorStatus\x12 \n" +
	"\tclient_id\x18\x0e \x01(\tH\x00R\bclientId\x88\x01\x01B\f\n" +
	"\n" +
	"_client_id\"\x9f\x01\n" +
	"\x10AnchorStatusInfo\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.dsa.veil.v1.AnchorStatusR\x06status\x12\x1a\n" +
	"\battempts\x18\x02 \x01(\rR\battempts\x12\x1d\n" +
	"\n" +
	"last_error\x18\x03 \x01(\tR\tlastError\x12\x1d\n" +
	"\n" +
	"human_note\x18\x04 \x01(\tR\thumanNote\"\xd8\x03\n" +
	"\x12VerificationResult\x12)\n" +
	"\x10signatures_valid\x18\x01 \x01(\bR\x0fsignaturesValid\x12=\n" +
	"\fcompleteness\x18\x02 \x01(\x0e2\x19.dsa.veil.v1.CompletenessR\fcompleteness\x12)\n" +
	"\x10missing_services\x18\x03 \x03(\tR\x0fmissingServices\x12/\n" +
	"\x13temporal_consistent\x18\x04 \x01(\bR\x12temporalConsistent\x12<\n" +
	"\x1adata_visibility_consistent\x18\x05 \x01(\bR\x18dataVisibilityConsistent\x12-\n" +
	"\x12isolation_verified\x18\x06 \x01(\bR\x11isolationVerified\x12/\n" +
	"\bqi_score\x18\a \x01(\v2\x14.dsa.veil.v1.QIScoreR\aqiScore\x12=\n" +
	"\x0foverall_verdict\x18\b \x01(\x0e2\x14.dsa.veil.v1.VerdictR\x0eoverallVerdict\x12\x1f\n" +
	"\vbyok_exempt\x18\t \x01(\bR\n" +
	"byokExempt\"\xdc\x01\n" +
	"\x13ExternalAttestation\x12?\n" +
	"\ttimestamp\x18\x01 \x01(\v2!.dsa.veil.v1.TimestampAttestationR\ttimestamp\x12L\n" +
	"\x10transparency_log\x18\x02 \x01(\v2!.dsa.veil.v1.TransparencyLogEntryR\x0ftransparencyLog\x126\n" +
	"\x06notary\x18\x03 \x01(\v2\x1e.dsa.veil.v1.NotaryAttestationR\x06notary\"\x9f\x01\n" +
	"\x14TimestampAttestation\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12'\n" +
	"\x0ftimestamp_token\x18\x02 \x01(\fR\x0etimestampToken\x12\x1b\n" +
	"\tcert_hash\x18\x03 \x01(\fR\bcertHash\x12%\n" +
	"\x0ehash_algorithm\x18\x04 \x01(\tR\rhashAlgorithm\"\xc7\x01\n" +
	"\x14TransparencyLogEntry\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1b\n" +
	"\tlog_index\x18\x02 \x01(\x03R\blogIndex\x12'\n" +
	"\x0finclusion_proof\x18\x03 \x01(\fR\x0einclusionProof\x124\n" +
	"\x16signed_entry_timestamp\x18\x04 \x01(\fR\x14signedEntryTimestamp\x12\x17\n" +
	"\alog_url\x18\x05 \x01(\tR\x06logUrl\"\xf3\x01\n" +
	"\x11NotaryAttestation\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12)\n" +
	"\x10notary_signature\x18\x02 \x01(\fR\x0fnotarySignature\x12/\n" +
	"\x14notary_public_key_id\x18\x03 \x01(\tR\x11notaryPublicKeyId\x12)\n" +
	"\x10checks_performed\x18\x04 \x03(\tR\x0fchecksPerformed\x12;\n" +
	"\vattested_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"attestedAt\"\xb2\x01\n" +
	"\x12FormalVerification\x12\x1b\n" +
	"\tspec_hash\x18\x01 \x01(\tR\bspecHash\x12\x1d\n" +
	"\n" +
	"proof_hash\x18\x02 \x01(\tR\tproofHash\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x12;\n" +
	"\vverified_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\"\xd2\x01\n" +
	"\x14MerkleInclusionProof\x12\x1b\n" +
	"\ttree_size\x18\x01 \x01(\x04R\btreeSize\x12\x1d\n" +
	"\n" +
	"leaf_index\x18\x02 \x01(\x04R\tleafIndex\x12\x1f\n" +
	"\vpath_hashes\x18\x03 \x03(\fR\n" +
	"pathHashes\x12\x19\n" +
	"\bis_right\x18\x04 \x03(\bR\aisRight\x12\x1b\n" +
	"\troot_hash\x18\x05 \x01(\fR\brootHash\x12%\n" +
	"\x0eroot_signature\x18\x06 \x01(\fR\rrootSignature\"w\n" +
	"\x14TransparencyLogProof\x12\x19\n" +
	"\blog_name\x18\x01 \x01(\tR\alogName\x12\x1b\n" +
	"\tlog_index\x18\x02 \x01(\x04R\blogIndex\x12'\n" +
	"\x0finclusion_proof\x18\x03 \x01(\fR\x0einclusionProof\"\xdc\x01\n" +
	"\x0eAuditIntegrity\x12\x1f\n" +
	"\vmerkle_root\x18\x01 \x01(\fR\n" +
	"merkleRoot\x12\x1b\n" +
	"\ttree_size\x18\x02 \x01(\x04R\btreeSize\x12J\n" +
	"\x0finclusion_proof\x18\x03 \x01(\v2!.dsa.veil.v1.MerkleInclusionProofR\x0einclusionProof\x12@\n" +
	"\n" +
	"log_proofs\x18\x04 \x03(\v2!.dsa.veil.v1.TransparencyLogProofR\tlogProofs\"\x83\x02\n" +
	"\rPrivacyBudget\x12)\n" +
	"\x10epsilon_consumed\x18\x01 \x01(\x01R\x0fepsilonConsumed\x12+\n" +
	"\x11epsilon_remaining\x18\x02 \x01(\x01R\x10epsilonRemaining\x124\n" +
	"\x16budget_utilization_pct\x18\x03 \x01(\x01R\x14budgetUtilizationPct\x125\n" +
	"\x16reidentification_bound\x18\x04 \x01(\x01R\x15reidentificationBound\x12-\n" +
	"\x12composition_method\x18\x05 \x01(\tR\x11compositionMethod\"t\n" +
	"\x15GetCertificateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12<\n" +
	"\fwait_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vwaitTimeout\"\x8c\x01\n" +
	"\rExportRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to*\xa9\x01\n" +
	"\tClaimType\x12\x1a\n" +
	"\x16CLAIM_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCLAIM_TYPE_TOKEN_GENERATED\x10\x01\x12\x1c\n" +
	"\x18CLAIM_TYPE_PII_SANITIZED\x10\x02\x12\"\n" +
	"\x1eCLAIM_TYPE_INFERENCE_COMPLETED\x10\x03\x12\x1e\n" +
	"\x1aCLAIM_TYPE_EVENTS_RECORDED\x10\x04*\xac\x01\n" +
	"\x14IsolationProbeStatus\x12\x1b\n" +
	"\x17ISOLATION_PROBE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18ISOLATION_PROBE_VERIFIED\x10\x01\x12\x1c\n" +
	"\x18ISOLATION_PROBE_BREACHED\x10\x02\x12\x1a\n" +
	"\x16ISOLATION_PROBE_LOCKED\x10\x03\x12\x1f\n" +
	"\x1bISOLATION_PROBE_BYOK_EXEMPT\x10\x04*l\n" +
	"\tQIVerdict\x12\x16\n" +
	"\x12QI_VERDICT_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fQI_VERDICT_PASS\x10\x01\x12\x1a\n" +
	"\x16QI_VERDICT_GENERALIZED\x10\x02\x12\x16\n" +
	"\x12QI_VERDICT_BLOCKED\x10\x03*]\n" +
	"\fCompleteness\x12\x1c\n" +
	"\x18COMPLETENESS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11COMPLETENESS_FULL\x10\x01\x12\x18\n" +
	"\x14COMPLETENESS_PARTIAL\x10\x02*a\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10VERDICT_VERIFIED\x10\x01\x12\x13\n" +
	"\x0fVERDICT_PARTIAL\x10\x02\x12\x12\n" +
	"\x0eVERDICT_FAILED\x10\x03*~\n" +
	"\fAnchorStatus\x12\x1d\n" +
	"\x19ANCHOR_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ANCHOR_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16ANCHOR_STATUS_ANCHORED\x10\x02\x12\x18\n" +
	"\x14ANCHOR_STATUS_FAILED\x10\x032\x92\x02\n" +
	"\x16VeilCertificateService\x12R\n" +
	"\x0eGetCertificate\x12\".dsa.veil.v1.GetCertificateRequest\x1a\x1c.dsa.veil.v1.VeilCertificate\x12P\n" +
	"\x12ExportCertificates\x12\x1a.dsa.veil.v1.ExportRequest\x1a\x1c.dsa.veil.v1.VeilCertificate0\x01\x12R\n" +
	"\x11VerifyCertificate\x12\x1c.dsa.veil.v1.VeilCertificate\x1a\x1f.dsa.veil.v1.VerificationResultBcZagithub.com/Declade/lucairn-enterprise-deployment-kit/apps/dashboard/internal/witness/pb;witnesspbb\x06proto3"

var (
	file_witness_proto_rawDescOnce sync.Once
	file_witness_proto_rawDescData []byte
)

func file_witness_proto_rawDescGZIP() []byte {
	file_witness_proto_rawDescOnce.Do(func() {
		file_witness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_witness_proto_rawDesc), len(file_witness_proto_rawDesc)))
	})
	return file_witness_proto_rawDescData
}

var file_witness_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_witness_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_witness_proto_goTypes = []any{
	(ClaimType)(0),                // 0: dsa.veil.v1.ClaimType
	(IsolationProbeStatus)(0),     // 1: dsa.veil.v1.IsolationProbeStatus
	(QIVerdict)(0),                // 2: dsa.veil.v1.QIVerdict
	(Completeness)(0),             // 3: dsa.veil.v1.Completeness
	(Verdict)(0),                  // 4: dsa.veil.v1.Verdict
	(AnchorStatus)(0),             // 5: dsa.veil.v1.AnchorStatus
	(*EntityCount)(nil),           // 6: dsa.veil.v1.EntityCount
	(*VeilClaim)(nil),             // 7: dsa.veil.v1.VeilClaim
	(*BridgeClaim)(nil),           // 8: dsa.veil.v1.BridgeClaim
	(*SanitizerClaim)(nil),        // 9: dsa.veil.v1.SanitizerClaim
	(*QIScore)(nil),               // 10: dsa.veil.v1.QIScore
	(*InferenceClaim)(nil),        // 11: dsa.veil.v1.InferenceClaim
	(*AuditClaim)(nil),            // 12: dsa.veil.v1.AuditClaim
	(*VeilCertificate)(nil),       // 13: dsa.veil.v1.VeilCertificate
	(*AnchorStatusInfo)(nil),      // 14: dsa.veil.v1.AnchorStatusInfo
	(*VerificationResult)(nil),    // 15: dsa.veil.v1.VerificationResult
	(*ExternalAttestation)(nil),   // 16: dsa.veil.v1.ExternalAttestation
	(*TimestampAttestation)(nil),  // 17: dsa.veil.v1.TimestampAttestation
	(*TransparencyLogEntry)(nil),  // 18: dsa.veil.v1.TransparencyLogEntry
	(*NotaryAttestation)(nil),     // 19: dsa.veil.v1.NotaryAttestation
	(*FormalVerification)(nil),    // 20: dsa.veil.v1.FormalVerification
	(*MerkleInclusionProof)(nil),  // 21: dsa.veil.v1.MerkleInclusionProof
	(*TransparencyLogProof)(nil),  // 22: dsa.veil.v1.TransparencyLogProof
	(*AuditIntegrity)(nil),        // 23: dsa.veil.v1.AuditIntegrity
	(*PrivacyBudget)(nil),         // 24: dsa.veil.v1.PrivacyBudget
	(*GetCertificateRequest)(nil), // 25: dsa.veil.v1.GetCertificateRequest
	(*ExportRequest)(nil),         // 26: dsa.veil.v1.ExportRequest
	(*timestamppb.Timestamp)(nil), // 27: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 28: google.protobuf.Duration
}
var file_witness_proto_depIdxs = []int32{
	0,  // 0: dsa.veil.v1.VeilClaim.claim_type:type_name -> dsa.veil.v1.ClaimType
	8,  // 1: dsa.veil.v1.VeilClaim.bridge:type_name -> dsa.veil.v1.BridgeClaim
	9,  // 2: dsa.veil.v1.VeilClaim.sanitizer:type_name -> dsa.veil.v1.SanitizerClaim
	11, // 3: dsa.veil.v1.VeilClaim.inference:type_name -> dsa.veil.v1.InferenceClaim
	12, // 4: dsa.veil.v1.VeilClaim.audit:type_name -> dsa.veil.v1.AuditClaim
	27, // 5: dsa.veil.v1.VeilClaim.timestamp:type_name -> google.protobuf.Timestamp
	10, // 6: dsa.veil.v1.SanitizerClaim.qi_score:type_name -> dsa.veil.v1.QIScore
	6,  // 7: dsa.veil.v1.SanitizerClaim.entity_counts:type_name -> dsa.veil.v1.EntityCount
	2,  // 8: dsa.veil.v1.QIScore.verdict:type_name -> dsa.veil.v1.QIVerdict
	1,  // 9: dsa.veil.v1.InferenceClaim.isolation_probe:type_name -> dsa.veil.v1.IsolationProbeStatus
	7,  // 10: dsa.veil.v1.VeilCertificate.claims:type_name -> dsa.veil.v1.VeilClaim
	15, // 11: dsa.veil.v1.VeilCertificate.verification:type_name -> dsa.veil.v1.VerificationResult
	16, // 12: dsa.veil.v1.VeilCertificate.attestation:type_name -> dsa.veil.v1.ExternalAttestation
	27, // 13: dsa.veil.v1.VeilCertificate.issued_at:type_name -> google.protobuf.Timestamp
	20, // 14: dsa.veil.v1.VeilCertificate.formal_verification:type_name -> dsa.veil.v1.FormalVerification
	23, // 15: dsa.veil.v1.VeilCertificate.audit_integrity:type_name -> dsa.veil.v1.AuditIntegrity
	24, // 16: dsa.veil.v1.VeilCertificate.privacy_budget:type_name -> dsa.veil.v1.PrivacyBudget
	14, // 17: dsa.veil.v1.VeilCertificate.anchor_status:type_name -> dsa.veil.v1.AnchorStatusInfo
	5,  // 18: dsa.veil.v1.AnchorStatusInfo.status:type_name -> dsa.veil.v1.AnchorStatus
	3,  // 19: dsa.veil.v1.VerificationResult.completeness:type_name -> dsa.veil.v1.Completeness
	10, // 20: dsa.veil.v1.VerificationResult.qi_score:type_name -> dsa.veil.v1.QIScore
	4,  // 21: dsa.veil.v1.VerificationResult.overall_verdict:type_name -> dsa.veil.v1.Verdict
	17, // 22: dsa.veil.v1.ExternalAttestation.timestamp:type_name -> dsa.veil.v1.TimestampAttestation
	18, // 23: dsa.veil.v1.ExternalAttestation.transparency_log:type_name -> dsa.veil.v1.TransparencyLogEntry
	19, // 24: dsa.veil.v1.ExternalAttestation.notary:type_name -> dsa.veil.v1.NotaryAttestation
	27, // 25: dsa.veil.v1.NotaryAttestation.attested_at:type_name -> google.protobuf.Timestamp
	27, // 26: dsa.veil.v1.FormalVerification.verified_at:type_name -> google.protobuf.Timestamp
	21, // 27: dsa.veil.v1.AuditIntegrity.inclusion_proof:type_name -> dsa.veil.v1.MerkleInclusionProof
	22, // 28: dsa.veil.v1.AuditIntegrity.log_proofs:type_name -> dsa.veil.v1.TransparencyLogProof
	28, // 29: dsa.veil.v1.GetCertificateRequest.wait_timeout:type_name -> google.protobuf.Duration
	27, // 30: dsa.veil.v1.ExportRequest.from:type_name -> google.protobuf.Timestamp
	27, // 31: dsa.veil.v1.ExportRequest.to:type_name -> google.protobuf.Timestamp
	25, // 32: dsa.veil.v1.VeilCertificateService.GetCertificate:input_type -> dsa.veil.v1.GetCertificateRequest
	26, // 33: dsa.veil.v1.VeilCertificateService.ExportCertificates:input_type -> dsa.veil.v1.ExportRequest
	13, // 34: dsa.veil.v1.VeilCertificateService.VerifyCertificate:input_type -> dsa.veil.v1.VeilCertificate
	13, // 35: dsa.veil.v1.VeilCertificateService.GetCertificate:output_type -> dsa.veil.v1.VeilCertificate
	13, // 36: dsa.veil.v1.VeilCertificateService.ExportCertificates:output_type -> dsa.veil.v1.VeilCertificate
	15, // 37: dsa.veil.v1.VeilCertificateService.VerifyCertificate:output_type -> dsa.veil.v1.VerificationResult
	35, // [35:38] is the sub-list for method output_type
	32, // [32:35] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_witness_proto_init() }
func file_witness_proto_init() {
	if File_witness_proto != nil {
		return
	}
	file_witness_proto_msgTypes[1].OneofWrappers = []any{
		(*VeilClaim_Bridge)(nil),
		(*VeilClaim_Sanitizer)(nil),
		(*VeilClaim_Inference)(nil),
		(*VeilClaim_Audit)(nil),
	}
	file_witness_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_witness_proto_rawDesc), len(file_witness_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_witness_proto_goTypes,
		DependencyIndexes: file_witness_proto_depIdxs,
		EnumInfos:         file_witness_proto_enumTypes,
		MessageInfos:      file_witness_proto_msgTypes,
	}.Build()
	File_witness_proto = out.File
	file_witness_proto_goTypes = nil
	file_witness_proto_depIdxs = nil
}
