apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: dsa
    app.kubernetes.io/component: observability
type: Opaque
data:
  admin-password: {{ .Values.secrets.values.grafanaAdminPassword | b64enc | quote }}
