apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-storage
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: dsa
    app.kubernetes.io/component: observability
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.loki.storageClass }}
  storageClassName: {{ .Values.loki.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.loki.storageSize }}
