apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: dsa
    app.kubernetes.io/component: observability
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3200
      targetPort: http
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: tempo
