apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-storage
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: dsa
    app.kubernetes.io/component: observability
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.tempo.storageClass }}
  storageClassName: {{ .Values.tempo.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.tempo.storageSize }}
