{{- if eq .Values.global.secrets.backend "vault" }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: dsa-secret-store
spec:
  provider:
    vault:
      server: {{ .Values.global.secrets.vault.endpoint | quote }}
      path: {{ .Values.global.secrets.vault.mountPath | quote }}
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ .Values.global.secrets.vault.role | quote }}
{{- else if eq .Values.global.secrets.backend "aws" }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: dsa-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.global.secrets.aws.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.global.secrets.aws.serviceAccount.name | quote }}
            namespace: {{ .Values.global.secrets.aws.serviceAccount.namespace | quote }}
{{- else if eq .Values.global.secrets.backend "azure" }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: dsa-secret-store
spec:
  provider:
    azurekv:
      vaultUrl: "https://{{ .Values.global.secrets.azure.keyVaultName }}.vault.azure.net"
      tenantId: {{ .Values.global.secrets.azure.tenantId | quote }}
      authType: ManagedIdentity
{{- end }}
