apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: dsa
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: http
      name: http
    - port: {{ .Values.service.healthPort }}
      targetPort: health
      name: health
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
